In [1]:
import tensorflow as tf
import numpy as np
np.__version__

D:\ppp\envs\gputf\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\ppp\envs\gputf\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\ppp\envs\gputf\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\ppp\envs\gputf\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a

'1.18.1'

In [6]:
tf.__version__

'1.14.0'

In [15]:
t = (1, 2, 3, 4, 5, 6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [16]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(6,)
4
6
int32


In [10]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.shape)
print(tensor.dtype)
tensor

Tensor("Rank_4:0", shape=(), dtype=int32)
(4,)
<dtype: 'int32'>


<tf.Tensor 'Const_5:0' shape=(4,) dtype=int32>

In [17]:
a = np.zeros((3,2))
a = np.zeros(shape=(4,4), dtype=np.uint8)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [18]:
a.shape

(4, 4)

In [19]:
len(a.shape)

2

In [12]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor 'zeros:0' shape=(3, 2) dtype=float32>

In [22]:
a = np.ones((4,2, 3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
a_tf = tf.ones((4, 2), dtype=tf.int64)
a_tf

<tf.Tensor 'ones:0' shape=(4, 2) dtype=int64>

In [25]:
a = np.full((1, 3), 7)
a

array([[7, 7, 7]])

In [26]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor 'Const_6:0' shape=(1, 3) dtype=int32>

In [28]:
s = np.array([[1,2,3], [4, 5, 6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [64]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [33]:
a = np.zeros((256, 128, 3))
print(a.shape)
a

(256, 128, 3)


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
A = np.arange(0, 12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
A_tf = tf.constant(tf.range(0, 12), shape=(3,4))
A_tf

TypeError: List of Tensors when single Tensor expected

In [41]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0, 2]}"')
print(f'A[0][2] is "{A[0][2]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [44]:
A[2,2]

10

In [45]:
A[2,2]=77
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 77, 11]])

In [46]:
print(A)
A[1:3, 1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]


array([[ 5,  6],
       [ 9, 77]])

In [47]:
A[1:3, 1:3] = 77
A

array([[ 0,  1,  2,  3],
       [ 4, 77, 77,  7],
       [ 8, 77, 77, 11]])

In [55]:
print(A)
A[1:3, 1:3] = 3* A[1:3, 1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
A = np.random.rand(3, 4)
print(A.dtype)
A

float64


array([[0.95619056, 0.30075295, 0.76002512, 0.47590006],
       [0.60518375, 0.65996836, 0.87617034, 0.80419236],
       [0.29731804, 0.32052142, 0.9423042 , 0.9359166 ]])

In [62]:
A = np.random.randn(10, 9)
print(A.shape)
print(np.mean(A))
print(np.std(A))

(10, 9)
-0.050529687833586315
1.0601288933259694


In [65]:
print(a)
a.dtype

[[3 3 3]
 [3 3 3]]


dtype('int32')

In [69]:
c = a.astype('float32')
print(a.dtype)
print(a)
print(c)
print(id(a))
print(id(c))

int32
[[3 3 3]
 [3 3 3]]
[[3. 3. 3.]
 [3. 3. 3.]]
2257460094896
2257460096336


In [71]:
a.astype(np.float64)

array([[3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
v = np.arange(4)
print(v, v.shape)
a = v.reshape(2,2)
print(a)
a[0] = 777
print(v)
print(a)

In [74]:
b= np.arange(10, 14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [80]:
a = np.arange(0, 10, 2)
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
print(b)
c = a.reshape((5, 1))
print(c, c.shape)

(5,)
(1, 5)
[[0 2 4 6 8]]
[[0]
 [2]
 [4]
 [6]
 [8]] (5, 1)


In [82]:
a = np.arange(1, 10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))
print(b.shape, id(b))
b

(3, 3) 2257459693008
(9,) 2257459330064


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* 8 by 4로 된 matrix를 만들것.
* 해당 matrix는 2부터 시작해서 짝수들로 64보다 작거나 같은 수로 채워짐. 행부터 채울것.
* 해당 matrix를 출력하고 나서 vector로 만들것(shape=(32,)인 np.array)

In [91]:
two = np.arange(2, 65, 2).reshape(8, 4)
print(two)
two = two.ravel()
print(two)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


In [94]:
c = a.T
print(a)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [96]:
print(a)
c = a*20
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


In [97]:
a = np.ones((5,3))
c = a+np.array([3, 4, 5])
print(c)


[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [99]:
b = np.array([3, 4, 5, 6, 7])
print(b.shape)
c = a+b
print(c)

(5,)


ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [100]:
b = np.array([3, 4, 5, 6, 7])
b = b.reshape(5,1)
c = a+b
print(a.shape)
print(b.shape)
print(c)

(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]
