In [61]:
import tensorflow as tf
import numpy as np
np.__version__

'1.18.5'

In [62]:
tf.__version__

'2.3.0'

`np.array ( list [,dtype])`

* list등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `floast32` : float (32bit)

In [63]:
t = (1,2,3,4)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [64]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(4,)
8
4
int64


In [65]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(4,)
<dtype: 'int64'>


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

# 특정 값으로 초기화한 `ndarray` 생성

`zeros`,`ones`, and `full`

In [66]:
a = np.zeros((3,2))
a = np.zeros(shape=(4,4), dtype = np.unit8)
a

AttributeError: ignored

In [67]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [68]:
a = np.ones((4,2,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [70]:
a = np.full((1,3),255)
a

array([[255, 255, 255]])

In [71]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[255, 255, 255]])>

# 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성

`zeros_like`, `ones_like`, and `full_like` 

In [72]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [73]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [74]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [75]:
b = np.zeros((256,128,3))
b.shape

(256, 128, 3)

# indexing & slicing

`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능함.

* list등의 python의 fundamental type들과의 차이는 slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing으로 실제로 원본이 수정되게 됨. (주의 필요.)

In [76]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [78]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [79]:
A[2,2]

10

In [80]:
A_tf[0,2] # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [81]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [82]:
print(A)
A[1:3,::-1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [83]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

# 난수 생성.

`np.random.rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
* d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.

`np.random.randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.


In [85]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[4.48971421e-01, 1.81856855e-01, 6.42719695e-01, 2.66396146e-01],
       [7.19469318e-01, 4.12274470e-01, 9.68572548e-01, 2.14184602e-01],
       [9.40147440e-01, 2.19581309e-01, 4.10842817e-01, 5.45234571e-04]])

In [86]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.23002803, 0.57925904, 0.9968734 , 0.6796812 ],
       [0.5773407 , 0.31712365, 0.65182257, 0.07163548],
       [0.9518001 , 0.83803236, 0.9906995 , 0.7229116 ]], dtype=float32)>

In [91]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))

(3, 4)
0.03804589548594539 1.0127594218561926


In [92]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
A_tf

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.55617416, 0.7732357 ]], dtype=float32)>

# `ndarray`의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [93]:
print(a)
a.dtype

[[3 3 3]
 [3 3 3]]


dtype('int64')

In [95]:
c = a.astype('float32')
print(a.dtype)
print(c)
print(id(a))
print(id(c))

int64
[[3. 3. 3.]
 [3. 3. 3.]]
140110001737120
140110000882992


In [96]:
c_tf = tf.dtypes.cast(c,tf.float32)
c_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [97]:
c = np.uint8(a)
print(c.dtype)
c
print(id(a))
print(id(c))

uint8
140110001737120
140110000882272


In [98]:
c = np.uint64(a)
print(a.dtype)
c
print(c.dtype)

int64
uint64


# `shape`변경

`ndarray.reshape(new_hsape)`

In [102]:
v = np.arange(4)
print(v,v.shape)
a =v.reshape(2,2)
a
a[0] = 777
print(v)
print(a)

[0 1 2 3] (4,)
[777 777   2   3]
[[777 777]
 [  2   3]]


In [103]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [105]:
a = np.arange(0,10,2) #[s:e:step_size]
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
b
c = a.reshape((5,1))
print(c.shape)

(5,)
(1, 5)
(5, 1)


In [106]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


# ndarray를 1차원으로 풀어내기

`ndarray.ravel()`

In [ ]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 140300165615488
(9,) 140300165615088


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<수업중간 실습>
* 8 by 4로 된 matrix를 만들것.
* 해당 matrix는 2부터 시작해서 짝수들로 64보다 작거나 같은 수로 채워짐. 행부터 채울것.
* 해당 matrix를 출력하고 나서 vector로 만들것 (shape=(32,)인 np.array)

In [118]:
y = np.arange(2,65,2).reshape((8,4))
print(y)

Y=y.ravel().reshape(32,)
Y

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

In [125]:
a = np.ones((5,3))
c = a + np.array([3,4,5])
print(c)

print(np.array([3,4,5]).shape)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
(3,)


In [128]:
b+np.array([3,4,5,6,7])
print(b.shape)
c = a + b
print(c)

(5,)


ValueError: ignored

In [129]:
b+np.array([3,4,5,6,7])
b = b.reshape(5,1)
c = a+b
print(a.shape)
print(b.shape)
print(c)

(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


# Transpose

`ndarray.T`

In [ ]:
c=a.T
print(id(a))
print(id(c))
c

140300165615488
140300165728576


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나. 

In [119]:
print(a)
c = a+2
print(c)

[0 2 4 6 8]
[ 2  4  6  8 10]


In [121]:
a = np.ones((5,3))
c = a+np.array([3,4,5])
print(c)

b= np.array([3,4,5,6,7])
c = a+(b[:,np.newaxis])
print(b[:,np.newaxis].shape)
print(c)

c = a+np.array([3,4,5,6,7])
print(c)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


ValueError: ignored

In [ ]:
np.concatenate((a,b),0)

In [ ]:
np.vstack((a,b))

In [ ]:
np.concatenate((a,b),1)
np.hstack((a,b))

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,22).reshape(4,3)
print(a.shape)
print(b.shape)

In [ ]:
c=np.stack((a,b),0)
print(c.shape)
c

In [ ]:
c=np.stack((a,b),1)
print(c.shape)
c

In [ ]:
c=np.stack((a,b),2)
print(c.shape)
c

In [ ]:
c=np.stack((a,b),-1)
print(c.shape)
c

In [ ]:
a = np.arange(12)
a

In [ ]:
np.hsplit(a,3)

In [ ]:
np.hsplit(a,[3,5])

In [ ]:
b = np.arage

In [ ]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])


In [ ]:
import scipy.linalg as sl


In [ ]:
sl.lu(A)

In [ ]:
P, L, U = sl.lu(A)

In [ ]:
U

In [ ]:
L

In [ ]:
np.linalg.inv(L)

In [ ]:
L@U

In [ ]:
P@L