<a href="https://colab.research.google.com/github/dsaint31x/OpenCV_Python_Tutorial/blob/master/DIP/2021/%EC%9D%B4%EA%B0%80%EC%9D%80/210910_DIP_Numpy01_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
np.__version__

'1.19.5'

In [ ]:
tf.__version__

'2.6.0'

`np.array ( list [,dtype])`

* list등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `floast32` : float (32bit)

In [ ]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [ ]:
print(a)
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

[1 2 3 4 5 6]
1
(6,)
8
6
int64


In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int64'>


<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>

# 특정 값으로 초기화한 `ndarray` 생성

`zeros`,`ones`, and `full`

In [ ]:
a = np.zeros((3,2))
a = np.zeros(shape=(4,4),dtype=np.uint8)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [ ]:
len(a.shape)

2

In [ ]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a = np.ones((4,2,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [ ]:
a = np.full((1,3),255)
a

array([[255, 255, 255]])

In [ ]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[255, 255, 255]])>

# 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성

`zeros_like`, `ones_like`, and `full_like` 

In [ ]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

# indexing & slicing

`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능함.

* list등의 python의 fundamental type들과의 차이는 slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing으로 실제로 원본이 수정되게 됨. (주의 필요.)

In [ ]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [ ]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [ ]:
A[2,2]

10

In [ ]:
A[2,2] = 77
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 77, 11]])

In [ ]:
A_tf[0,2] # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [ ]:
print(A)
A[1:3,1:3] = 3*A[1:3,1:3] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]


In [ ]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

# 난수 생성.

`np.random.rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
* d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.

`np.random.randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.


In [ ]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.98540596, 0.30058202, 0.95855178, 0.50703975],
       [0.68445491, 0.24468816, 0.97530147, 0.34166945],
       [0.34412055, 0.54916915, 0.83315199, 0.91146033]])

##### 텐서플로우에서 random 함수로 균일분포 난수를 발생

In [ ]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.6522708 , 0.8900511 , 0.6225263 , 0.31574237],
       [0.9775747 , 0.55534685, 0.8013394 , 0.2605517 ],
       [0.30720043, 0.4664458 , 0.00624251, 0.5104612 ]], dtype=float32)>

In [ ]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A)
print(A.shape)
print(np.mean(A),np.std(A))

[[-1.45077865  0.17551097 -0.43582153 -1.42396905]
 [-2.35032222 -0.326537   -0.11404077  0.27540945]
 [-1.11400629 -1.52248791  0.79606071 -0.12059593]]
(3, 4)
-0.6342981864516305 0.887501779707354


##### 텐서플로우 random.normal 랜덤 정규분포 난수 함수

In [ ]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
# stddev : 표준 편차(standard deviation)는 분산을 제곱근
A_tf

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-2.3878808 ,  0.04392651]], dtype=float32)>

# `ndarray`의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [ ]:
print(a)
print(type(a))
a.dtype

[[3 3 3]
 [3 3 3]]
<class 'numpy.ndarray'>


dtype('int64')

In [ ]:
c = a.astype('float32')
print(a.dtype)
print(c)
print(id(a))
print(id(c))

int64
[[3. 3. 3.]
 [3. 3. 3.]]
139942595836224
139942551164448


In [ ]:
a.astype(np.float128)

array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float128)

In [ ]:
c_tf = tf.dtypes.cast(c,tf.float32)
c_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [ ]:
c = np.uint8(a)
print(c.dtype)
print(c)
print(id(a))
print(id(c))

uint8
[[3 3 3]
 [3 3 3]]
139942595836224
139942551849920


In [ ]:
c = np.uint64(a)
print(a.dtype)
print(c.dtype)
print(c)
print(id(a))
print(id(c))

int64
uint64
[[3 3 3]
 [3 3 3]]
139942595836224
139942551214800


# `shape`변경

`ndarray.reshape(new_shape)`

In [ ]:
v = np.arange(4)
print(v,v.shape)
a = v.reshape(2,2)
a
a[0]=777
print(v)
print(a)

[0 1 2 3] (4,)
[777 777   2   3]
[[777 777]
 [  2   3]]


In [ ]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [ ]:
a = np.arange(0,10,2) # [ s:e :step_size]
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
c = a.reshape((5,1))
print(c.shape)
print("a is ", a)
print("b is ", b)
print("c is ", c)

(5,)
(1, 5)
(5, 1)
a is  [0 2 4 6 8]
b is  [[0 2 4 6 8]]
c is  [[0]
 [2]
 [4]
 [6]
 [8]]


In [ ]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


# ndarray를 1차원으로 풀어내기

`ndarray.ravel()`

In [ ]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 139942485830912
(9,) 139942552226112


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Test01
 * 8 by 4 로 된 matrix를 만들것.
 * 해당 matrix는 2부터 시작해서 짝수들로 64보다 작거나 같은 수로 채워짐. 행부터 채울것.
 * 해당 matrix를 출력하고 나서 vector로  만들것 (shape=(32,)인 np.array)
 * 해당 vector를 다시 출력.


In [ ]:
matrix = np.arange(2,65,2).reshape(8,4)
print("matrix's shape : ", matrix.shape)
print("matrix is : \n", matrix)
print("------------------------------")
vector = matrix.ravel()
print("vector's shape : ", vector.shape)
print("vector's type : ", type(vector))
print("vector is : ", vector)

matrix's shape :  (8, 4)
matrix is : 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]
------------------------------
vector's shape :  (32,)
vector's type :  <class 'numpy.ndarray'>
vector is :  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


# Transpose

`ndarray.T`

In [ ]:
a = np.ones(shape = (3,3))

In [ ]:
c=a.T
print(a)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나. 

In [ ]:
print(a)
c = a/2
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [ ]:
a = np.ones( shape=(5,3) )
c = a + np.array([3,4,5])
print(c)

print(np.array([3,4,5]).shape)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
(3,)


In [ ]:
b= np.array([3,4,5,6,7])
print(b.shape)
c = a+b
print(c)

(5,)


ValueError: ignored

In [ ]:
b = np.array([3,4,5,6,7])
#b = b[:,np.newaxis]
b = b.reshape(5,1)
print(a)
c = a+b
print(a.shape)
print(b.shape)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [ ]:
c = a+np.array([3,4,5,6,7]).reshape((5,1))
print(c)

[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]
