<a href="https://colab.research.google.com/github/dsaint31x/OpenCV_Python_Tutorial/blob/master/DIP/2020/%EC%9D%B4%EC%A7%80%EC%9A%B0/3%EC%A3%BC%EC%B0%A8_DIP_Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import tensorflow as tf
import numpy as np
np.__version__

'1.18.5'

In [3]:
tf.__version__

'2.3.0'

`np.array ( list [,dtype])`

* list등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `floast32` : float (32bit)

In [5]:
t=(1,2,3,4)
a=np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [ ]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [6]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(4,)
8
4
int64


In [7]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(4,)
<dtype: 'int64'>


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

# 특정 값으로 초기화한 `ndarray` 생성

`zeros`,`ones`, and `full`

In [8]:
a = np.zeros((3,2)) #3행2열
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
a=np.zeros((4,4),dtype='uint8')
print(len(a.shape))
print(a)

2
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [13]:
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [15]:
a = np.full((1,3),7)
a

array([[7, 7, 7]])

In [17]:
a=np.full((1,3),266)
print(a)
print(a.shape)

[[266 266 266]]
(1, 3)


In [ ]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[7, 7, 7]])>

# 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성

`zeros_like`, `ones_like`, and `full_like` 

In [18]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [23]:
# 256x128x3 array (0으로 채워진)

a=np.zeros((256,128,3))
a.shape

(256, 128, 3)

# indexing & slicing

`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능함.

* list등의 python의 fundamental type들과의 차이는 slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing으로 실제로 원본이 수정되게 됨. (주의 필요.)

In [29]:
A = np.arange(0,12).reshape(3,4) #0부터 11까지 12개 숫자를 3행4열로 표현
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
#엥
A = np.arange(0,12).reshape(3,2,-1) 
A

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [27]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [30]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [33]:
A[2][2]

10

In [34]:
A[2,2]

10

In [ ]:
A_tf[0,2] # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [35]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [36]:
A[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [38]:
print(A)
A[1:3,0:4:2] #0부터 시작해서 4까지 한번증가할때 2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 4,  6],
       [ 8, 10]])

In [ ]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

# 난수 생성.

`np.random.rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
* d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.

`np.random.randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.


In [39]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.11190367, 0.90830614, 0.00174555, 0.27506956],
       [0.85389009, 0.83926203, 0.39300766, 0.03032238],
       [0.34049132, 0.59930112, 0.38789616, 0.01188697]])

In [40]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.49351954, 0.90996087, 0.81618786, 0.19029403],
       [0.49327374, 0.44759023, 0.01392198, 0.06269109],
       [0.35498905, 0.61397326, 0.00323045, 0.30959582]], dtype=float32)>

In [ ]:
A = np.random.randn(1,2) #normal distribution of which parameters are mean and standard deviation.
A

array([[-0.71279898, -1.78033241]])

In [43]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))

(3, 4)
-0.3792172960863387 0.8341915451968795


In [ ]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
A_tf

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-1.2632887 , -0.91719854]], dtype=float32)>

# `ndarray`의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [47]:
print(a)
a.dtype

[[3 3 3]
 [3 3 3]]


dtype('int64')

In [49]:
c = a.astype('float32')
print(a.dtype)
print(c)
print(id(a))
print(id(c))

int64
[[3. 3. 3.]
 [3. 3. 3.]]
140389351183904
140389351184704


In [50]:
c_tf = tf.dtypes.cast(c,tf.float32)
c_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [51]:
c = np.uint8(a)
print(c.dtype)
c
print(id(a))
print(id(c))

uint8
140389351183904
140389233126416


In [54]:
c = np.uint64(a)
print(a.dtype)
c
print(c.dtype)
c

int64
uint64


array([[3, 3, 3],
       [3, 3, 3]], dtype=uint64)

# `shape`변경

`ndarray.reshape(new_hsape)`

In [55]:
v = np.arange(4)
print(v,v.shape)
a=v.reshape(2,2)
a

[0 1 2 3] (4,)


array([[0, 1],
       [2, 3]])

In [ ]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [56]:
a[0]=777
print(v)
print(a)

[777 777   2   3]
[[777 777]
 [  2   3]]


In [57]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [58]:
a = np.arange(0,10,2) # [s:e:step_size]
b = a.reshape((1,5))
print(a.shape) #rank=1 벡터
print(b.shape) #rank=2 matrix
b

(5,)
(1, 5)


array([[0, 2, 4, 6, 8]])

In [ ]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


# ndarray를 1차원으로 풀어내기

`ndarray.ravel()`

In [59]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 140389231712336
(9,) 140389231712496


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 퀴즈: 
8*4로 된 matrix를 만들 것

해당 matrix는 2부터 시작해서 짝수들로 64보다 작거나 같은수로 채워짐

행부터 해울 것

해당 matrix를 출력하고 나서 벡터로 만들 것 shape=(32,)인 np.array

해당 벡터를 다시 출력

In [65]:
QUIZ=np.arange(2,65,2).reshape(8,4)
print(QUIZ)

quiz = QUIZ.ravel()
print(quiz)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


# Transpose

`ndarray.T`

In [71]:
a=np.ones((10,5), dtype='uint32')

In [72]:
c=a.T
print(id(a))
print(id(c))
c

140389231711456
140389231710336


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint32)

# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나. 

In [76]:
print(a)
c = a/2
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [78]:
print(a.shape)

(5, 3)


왜일까?

In [77]:
a = np.ones((5,3))
c = a+np.array([3,4,5])
print(c)



[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [79]:
b= np.array([3,4,5,6,7])
print(b.shape)
c=a+b
print(C)

(5,)


ValueError: ignored

reshape를 해줘야 한다는 거지

In [82]:
b= np.array([3,4,5,6,7])
#b=b[:np.newaxis]
b=b.reshape(5,1)
c=a+b
print(a.shape)
print(b.shape)
print(c)

(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [75]:
b= np.array([3,4,5,6,7])
c = a+(b[:,np.newaxis])
print(b[:,np.newaxis].shape)
print(c)



(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [ ]:
c = a+np.array([3,4,5,6,7])
print(c)

In [ ]:
np.concatenate((a,b),0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [ ]:
np.concatenate((a,b),1)
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,22).reshape(4,3)
print(a.shape)
print(b.shape)

(4, 3)
(4, 3)


In [ ]:
c=np.stack((a,b),0)
print(c.shape)
c

(2, 4, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]])

In [ ]:
c=np.stack((a,b),1)
print(c.shape)
c

(4, 2, 3)


array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[ 3,  4,  5],
        [13, 14, 15]],

       [[ 6,  7,  8],
        [16, 17, 18]],

       [[ 9, 10, 11],
        [19, 20, 21]]])

In [ ]:
c=np.stack((a,b),2)
print(c.shape)
c

(4, 3, 2)


array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]],

       [[ 9, 19],
        [10, 20],
        [11, 21]]])

In [ ]:
c=np.stack((a,b),-1)
print(c.shape)
c

(4, 3, 2)


array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]],

       [[ 9, 19],
        [10, 20],
        [11, 21]]])

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.hsplit(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
np.hsplit(a,[3,5])

[array([0, 1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [ ]:
b = np.arage

NameError: ignored

In [ ]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])


In [ ]:
import scipy.linalg as sl


In [ ]:
sl.lu(A)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]), array([[ 1. ,  0. ,  0. ],
        [ 0.5,  1. ,  0. ],
        [-0.5, -0.6,  1. ]]), array([[ 6. , -4. ,  0. ],
        [ 0. , -5. , -2. ],
        [ 0. ,  0. , -0.2]]))

In [ ]:
P, L, U = sl.lu(A)

In [ ]:
U

array([[ 6. , -4. ,  0. ],
       [ 0. , -5. , -2. ],
       [ 0. ,  0. , -0.2]])

In [ ]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [-0.5, -0.6,  1. ]])

In [ ]:
np.linalg.inv(L)

array([[ 1. ,  0. ,  0. ],
       [-0.5,  1. ,  0. ],
       [ 0.2,  0.6,  1. ]])

In [ ]:
L@U

array([[ 6., -4.,  0.],
       [ 3., -7., -2.],
       [-3.,  5.,  1.]])

In [ ]:
P@L

array([[ 0.5,  1. ,  0. ],
       [-0.5, -0.6,  1. ],
       [ 1. ,  0. ,  0. ]])