In [4]:
import tensorflow as tf
import numpy as np
print(np.__version__)
print(tf.__version__)

1.19.1
2.0.0


`np.array ( list [,dtype])`

* list등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `floast32` : float (32bit)

In [14]:
a = (((1,2,3,4),(1,2,3,4),(1,2,3,4)),((1,2,3,4),(1,2,3,4),(1,2,3,4)),((1,2,3,4),(1,2,3,4),(1,2,3,4)))
print(type(a))
a = np.array(a)
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [15]:
print(a.ndim)    # numberof dimension = Rank
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

3
(3, 3, 4)
4
36
int32


In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(4,)
<dtype: 'int64'>


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

# 특정 값으로 초기화한 `ndarray` 생성

`zeros`,`ones`, and `full`

In [23]:
a = np.zeros((3,2))
print(a.shape)
a

(3, 2)


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
a = np.zeros((4,4), dtype=np.uint8)
a.shape

(4, 4)

In [25]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: id=2, shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [26]:
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: id=5, shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)>

In [28]:
a = np.full((1,3),7)
a

array([[7, 7, 7]])

In [29]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor: id=6, shape=(1, 3), dtype=int32, numpy=array([[7, 7, 7]])>

# 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성

`zeros_like`, `ones_like`, and `full_like` 

In [30]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
task = np.zeros((256,128,3))

In [33]:
task.shape

(256, 128, 3)

In [34]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

# indexing & slicing

`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능함.

* list등의 python의 fundamental type들과의 차이는 slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing으로 실제로 원본이 수정되게 됨. (주의 필요.)

In [50]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: id=12, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [42]:
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')
print(f'A[1][2] is "{A[1][2]}"')

A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"
A[1][2] is "6"


In [43]:
A_tf[0,2] # scalar

<tf.Tensor: id=16, shape=(), dtype=int32, numpy=2>

In [44]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [52]:
A[1:3,::-1]

array([[ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [53]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

In [57]:
A[0:1,0:1] = 79
A

array([[ 79,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

# 난수 생성.

`np.random.rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
* d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.

`np.random.randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.


In [58]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.95267502, 0.52824106, 0.05018851, 0.29612327],
       [0.23188913, 0.19653073, 0.24259599, 0.10269412],
       [0.26141521, 0.13209374, 0.13241242, 0.31339298]])

In [59]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: id=23, shape=(3, 4), dtype=float32, numpy=
array([[0.75526273, 0.46855474, 0.03552878, 0.43853247],
       [0.00668299, 0.60052407, 0.14673316, 0.7756864 ],
       [0.9906843 , 0.40633225, 0.31270587, 0.9185045 ]], dtype=float32)>

In [69]:
A = np.random.randn(10,5) #normal distribution of which parameters are mean and standard deviation.
A

array([[-1.01251862, -0.40002209, -0.67210932,  0.12964163,  0.8660138 ],
       [ 0.88577672,  0.81752381,  1.19291783, -0.75327415, -1.29481335],
       [-0.34621262,  1.47825196,  0.26339293,  1.27615458,  1.17833508],
       [-0.41009793,  1.02241712,  0.78760825, -1.09424836, -0.02724515],
       [ 2.45520496, -0.89068052,  0.33674519,  1.22493246, -1.32739131],
       [ 0.48941328, -0.69704062,  0.03361989, -0.07992736, -0.88146103],
       [-0.19093133,  1.01914092,  0.24337917, -1.39004619, -0.389018  ],
       [ 1.48859516, -0.21203564, -1.09708512, -0.40259501, -0.08569169],
       [ 0.41849565,  0.1684682 , -0.45648469, -1.38570361,  0.24465417],
       [ 1.57142886,  0.2648839 , -0.73998692,  0.32740584, -0.01453689]])

In [70]:
print(type(A[0,1]))
print(np.mean(A), np.std(A))

<class 'numpy.float64'>
0.07866487596654859 0.8919986011837484


In [63]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
A_tf

<tf.Tensor: id=29, shape=(1, 2), dtype=float32, numpy=array([[-0.33771104, -0.93582475]], dtype=float32)>

# `ndarray`의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [71]:
print(a)
a.dtype

[[3 3 3]
 [3 3 3]]


dtype('int32')

In [72]:
c = a.astype('float32')
print(a.dtype)
c
print(id(a))
print(id(c))

int32
692032164368
692031890656


In [73]:
c_tf = tf.dtypes.cast(c,tf.float32)
c_tf

<tf.Tensor: id=30, shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [74]:
c = np.uint8(a)
print(c.dtype)
c
print(id(a))
print(id(c))

uint8
692032164368
692032580464


In [75]:
c = np.uint64(a)
print(a.dtype)
c
print(c.dtype)

int32
uint64


# `shape`변경

`ndarray.reshape(new_hsape)`

In [76]:
v = np.arange(4)
a = v.reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [77]:
a[0] = 77
print(v)
print(a)

[77 77  2  3]
[[77 77]
 [ 2  3]]


In [78]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [79]:
a = np.arange(0,10,2)
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
b

(5,)
(1, 5)


array([[0, 2, 4, 6, 8]])

In [80]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


# ndarray를 1차원으로 풀어내기

`ndarray.ravel()`

In [ ]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 140300165615488
(9,) 140300165615088


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
problem.ravel().shape

(32,)

In [88]:
start = 2
stop = 64
step = 2
row = 8
column = 4
problem = np.arange(start,stop+1,step).reshape(row,column)
print(problem)
print(problem.ravel())

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


# Transpose

`ndarray.T`

In [96]:
a = np.arange(0,20,2).reshape(2,-1)
c=a.T
print(id(a))
print(id(c))
c

692032562320
692032562240


array([[ 0, 10],
       [ 2, 12],
       [ 4, 14],
       [ 6, 16],
       [ 8, 18]])

# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나. 

In [97]:
print(a)
c = a+2
print(c)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [101]:
a = np.ones((5,3))
print(a)
c = a+np.array([3,4,5])
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [102]:
b= np.array([3,4,5,6,7])
print(b[:,np.newaxis]) # .reshape(5,1)
c = a+(b[:,np.newaxis])
print(b[:,np.newaxis].shape)
print(c)

[[3]
 [4]
 [5]
 [6]
 [7]]
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [100]:
c = a+np.array([3,4,5,6,7])
print(c)

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [ ]:
np.concatenate((a,b),0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [ ]:
np.concatenate((a,b),1)
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,22).reshape(4,3)
print(a.shape)
print(b.shape)

(4, 3)
(4, 3)


In [ ]:
c=np.stack((a,b),0)
print(c.shape)
c

(2, 4, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]])

In [ ]:
c=np.stack((a,b),1)
print(c.shape)
c

(4, 2, 3)


array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[ 3,  4,  5],
        [13, 14, 15]],

       [[ 6,  7,  8],
        [16, 17, 18]],

       [[ 9, 10, 11],
        [19, 20, 21]]])

In [ ]:
c=np.stack((a,b),2)
print(c.shape)
c

(4, 3, 2)


array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]],

       [[ 9, 19],
        [10, 20],
        [11, 21]]])

In [ ]:
c=np.stack((a,b),-1)
print(c.shape)
c

(4, 3, 2)


array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]],

       [[ 9, 19],
        [10, 20],
        [11, 21]]])

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.hsplit(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
np.hsplit(a,[3,5])

[array([0, 1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [ ]:
b = np.arage

NameError: ignored

In [ ]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])


In [ ]:
import scipy.linalg as sl


In [ ]:
sl.lu(A)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]), array([[ 1. ,  0. ,  0. ],
        [ 0.5,  1. ,  0. ],
        [-0.5, -0.6,  1. ]]), array([[ 6. , -4. ,  0. ],
        [ 0. , -5. , -2. ],
        [ 0. ,  0. , -0.2]]))

In [ ]:
P, L, U = sl.lu(A)

In [ ]:
U

array([[ 6. , -4. ,  0. ],
       [ 0. , -5. , -2. ],
       [ 0. ,  0. , -0.2]])

In [ ]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [-0.5, -0.6,  1. ]])

In [ ]:
np.linalg.inv(L)

array([[ 1. ,  0. ,  0. ],
       [-0.5,  1. ,  0. ],
       [ 0.2,  0.6,  1. ]])

In [ ]:
L@U

array([[ 6., -4.,  0.],
       [ 3., -7., -2.],
       [-3.,  5.,  1.]])

In [ ]:
P@L

array([[ 0.5,  1. ,  0. ],
       [-0.5, -0.6,  1. ],
       [ 1. ,  0. ,  0. ]])