In [1]:
import tensorflow as tf
import numpy as np
np.__version__

'1.18.5'

In [2]:
tf.__version__

'2.3.0'

In [3]:
import numpy as np

`np.array ( list [,dtype])`

* list등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `floast32` : float (32bit)

In [6]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [7]:
t=(1,2,3,4)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [8]:
print(a.ndim)   #number of dimension 축
print(a.shape)   #
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(4,)
8
4
int64


In [11]:
t=(1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [12]:
print(a.ndim)   #number of dimension 축
print(a.shape)   #dimension 구조
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(6,)
8
6
int64


In [13]:
#넘어가죠
tensor = tf.constant(a)
print(tf.rank(tensor))   #rank=ndim
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int64'>


<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>

# 특정 값으로 초기화한 `ndarray` 생성

`zeros`,`ones`, and `full`

In [14]:
a = np.zeros((3,2))   #3행 2열
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
a = np.zeros((3,2))   #3행 2열
a = np.zeros(shape=(4,4),dtype=np.uint8)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [16]:
a.shape

(4, 4)

In [17]:
len(a.shape)

2

In [18]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [20]:
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
a = np.ones((4,2,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
#넘어가
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [24]:
a = np.full((1,3),7)
a

array([[7, 7, 7]])

In [26]:
a = np.full((1,3),255)
a

array([[255, 255, 255]])

In [27]:
#넘어가
a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[255, 255, 255]])>

# 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성

`zeros_like`, `ones_like`, and `full_like` 

In [28]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [34]:
a = np.zeros((256,128,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# indexing & slicing

`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능함.

* list등의 python의 fundamental type들과의 차이는 slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing으로 실제로 원본이 수정되게 됨. (주의 필요.)

In [71]:
A = np.arange(0,12).reshape(3,4)   #arange=range
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
#A = np.arange(0,12).reshape(3,-1)   #-1:나머지는 니가 채워줘
#A

In [41]:
#A = np.arange(0,12).reshape(2,2,-1)   #arange=range
#A

In [43]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [45]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')   #아래랑 같음
print(f'A[0][2] is "{A[0][2]}"')   #위랑 같음

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [46]:
A[1]

array([4, 5, 6, 7])

In [47]:
A[2,2]

10

In [58]:
A[2,2]=77
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777,  77,  11]])

In [59]:
A_tf[0,2] # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [60]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[  0   1   2   3]
 [  4 777 777   7]
 [  8 777  77  11]]
A[1,2:] is "[777   7]"
A[1,::2] is "[  4 777]"
A[1,::-2] is "[  7 777]"
A[1,::-1] is "[  7 777 777   4]"
A[1,3:0:-1] is "[  7 777 777]"


In [64]:
print(A)
A[1:3,1:3]

[[  0   1   2   3]
 [  4 777 777   7]
 [  8 777  77  11]]


array([[777, 777],
       [777,  77]])

In [72]:
print(A)
A[1:3,::-1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [73]:
print(A)
A[1:3,::-1]=3*A[1:3,::-1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [70]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

# 난수 생성.

`np.random.rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
* d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.

`np.random.randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.


In [74]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.68732307, 0.92920527, 0.68886332, 0.14065172],
       [0.1706073 , 0.30257644, 0.99724323, 0.43431864],
       [0.63810133, 0.07504847, 0.65872527, 0.14127451]])

In [75]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.2923541 , 0.9449266 , 0.44981945, 0.328004  ],
       [0.14202201, 0.23297739, 0.47566962, 0.82950735],
       [0.03909338, 0.3677541 , 0.26142538, 0.10883665]], dtype=float32)>

In [76]:
A = np.random.randn(1,2) #normal distribution of which parameters are mean and standard deviation.
A

array([[ 0.86749417, -0.38756187]])

In [78]:
A = np.random.randn(10,9) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))

(10, 9)
-0.049119450881606054 1.0085084427124107


In [79]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))

(3, 4)
-0.14691210404096514 0.8491139891987463


In [80]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
A_tf

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.08392498,  0.48385012]], dtype=float32)>

# `ndarray`의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [81]:
print(a)
a.dtype

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


dtype('float64')

In [82]:
c = a.astype('float32')
print(a.dtype)
c
print(id(a))
print(id(c))

float64
140714201435232
140714082709792


In [84]:
c = a.astype('float32')
print(a.dtype)
print(c)
print(id(a))
print(id(c))

float64
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
140714201435232
140714081814048


In [85]:
a.astype(np.float128)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float128)

In [86]:
c_tf = tf.dtypes.cast(c,tf.float32)
c_tf

<tf.Tensor: shape=(256, 128, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [87]:
c = np.uint8(a)
print(c.dtype)
c
print(id(a))
print(id(c))

uint8
140714201435232
140714081815088


In [88]:
c = np.uint64(a)
print(a.dtype)
c
print(c.dtype)

float64
uint64


# `shape`변경

`ndarray.reshape(new_hsape)`

In [90]:
v=np.arange(4)
print(v,v.shape)
a=v.reshape(2,2)
a
a[0]=777
print(v)
print(a)

[0 1 2 3] (4,)
[777 777   2   3]
[[777 777]
 [  2   3]]


In [ ]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [91]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [92]:
a = np.arange(0,10,2)   #[start, end, step size]
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
b

(5,)
(1, 5)


array([[0, 2, 4, 6, 8]])

In [93]:
a = np.arange(0,10,2)   #[start, end, step size]
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
b
c=a.reshape((5,1))
print(c.shape)

(5,)
(1, 5)
(5, 1)


In [94]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


# ndarray를 1차원으로 풀어내기

`ndarray.ravel()`

In [95]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 140714081867056
(9,) 140714081868576


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
#test1

a = np.arange(2,65,2).reshape((8,4))
print(a)

b=a.ravel()
print(b)
b


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

# Transpose

`ndarray.T`

In [105]:
c=a.T
print(id(a))
print(id(c))
c

140714081868496
140714081869456


array([[ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나. 

In [106]:
print(a)
c = a+2
print(c)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]
[[ 4  6  8 10]
 [12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]
 [44 46 48 50]
 [52 54 56 58]
 [60 62 64 66]]


In [111]:
print(a)
c = a/2
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [112]:
a = np.ones((5,3))
c = a+np.array([3,4,5])
print(c)

#b= np.array([3,4,5,6,7])
#c = a+(b[:,np.newaxis])
#print(b[:,np.newaxis].shape)
#print(c)

#c = a+np.array([3,4,5,6,7])
#print(c)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [115]:
a = np.ones(shape=(5,3))
c = a+np.array([3,4,5])
print(c)

print(a+np.array([3,4,5]).shape)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [116]:
b= np.array([3,4,5,6,7])
#c = a+(b[:,np.newaxis])
b=b.reshape(5,1)
c=a+b
print(a.shape)
print(b.shape)
print(c)

(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [117]:
c = a+np.array([3,4,5,6,7]).reshape((5,1))
print(c)

[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [ ]:
np.concatenate((a,b),0)

In [ ]:
np.vstack((a,b))

In [ ]:
np.concatenate((a,b),1)
np.hstack((a,b))

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,22).reshape(4,3)
print(a.shape)
print(b.shape)

In [ ]:
c=np.stack((a,b),0)
print(c.shape)
c

In [ ]:
c=np.stack((a,b),1)
print(c.shape)
c

In [ ]:
c=np.stack((a,b),2)
print(c.shape)
c

In [ ]:
c=np.stack((a,b),-1)
print(c.shape)
c

In [ ]:
a = np.arange(12)
a

In [ ]:
np.hsplit(a,3)

In [ ]:
np.hsplit(a,[3,5])

In [ ]:
b = np.arage

In [ ]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])


In [ ]:
import scipy.linalg as sl


In [ ]:
sl.lu(A)

In [ ]:
P, L, U = sl.lu(A)

In [ ]:
U

In [ ]:
L

In [ ]:
np.linalg.inv(L)

In [ ]:
L@U

In [ ]:
P@L