<a href="https://colab.research.google.com/github/dsaint31x/OpenCV_Python_Tutorial/blob/master/DIP/DIP_Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import torch

In [2]:
np.__version__

'1.25.2'

In [3]:
tf.__version__

'2.15.0'

In [4]:
torch.__version__

'2.2.1+cu121'

In [5]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]


# 0.libary 설치 여부 및 colab 동작 여부 확인

In [6]:
import importlib
# Check if a module exists
try:
  module_name = "google.colab"
  if importlib.util.find_spec(module_name):
    print(f"{module_name} module exists.")
  else:
    print(f"{module_name} module does not exist.")
except ImportError:
  print(f"{module_name} module does not exist.")

# Check module location
try:
  module_spec = importlib.util.find_spec("torch")
  if module_spec:
    print(f"{module_spec.name} module is located at {module_spec.origin}.")
except ImportError:
  print(f"{module_name} module does not exist.")


google.colab module exists.
torch module is located at /usr/local/lib/python3.10/dist-packages/torch/__init__.py.


In [7]:
try:
    metadata = importlib.metadata.PackagePath(module_name)
    print(f"{module_name} 패키지가 존재합니다.")
    print(f"패키지 이름: {metadata.name}")
    print(f"패키지 버전: {metadata.locate}")
    print(f"패키지 버전: {importlib.metadata.version(module_name)}")

except importlib.metadata.PackageNotFoundError:
    print(f"{module_name} 패키지가 존재하지 않습니다.")

google.colab 패키지가 존재합니다.
패키지 이름: google.colab
패키지 버전: <bound method PackagePath.locate of PackagePath('google.colab')>
패키지 버전: 1.0.0


# 1.Tensor 생성하기


`np.array ( list [,dtype])`

* list 나 tuple 등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `float32` : float (32bit)

In [8]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [9]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(6,)
8
6
int64


In [10]:
a = np.array([1.,2.,3.])
print(a.dtype)
a = np.array([1.,2.,3.], dtype=int)
print(a.dtype)
a = np.array([1.,2.,3.], dtype=float)
print(a.dtype)

float64
int64
float64


tensorflow에서의 tensor 생성하기.

In [13]:
tensor = tf.constant(t)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
# print(tensor.itemsize)  #error. not supported
# print(tensor.size)      #error. not supported
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int32'>


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

pytorch에서의 tensor 생성하기

In [14]:
p = torch.tensor(t)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size())    # not attribute but method
print(p.dtype)


1
torch.Size([6])
8
torch.Size([6])
torch.int64


## 1-0. 기본 dtype

* numpy 의 경우, `float64` 와 `int64`
* tensorflow 의 경우, `float32` 와 `int32`
* torch 의 경우, `float32` 와 `int64`

In [16]:
print(np.array([1.,2.,3.]).dtype)
print(np.array([1,2,3]).dtype)
print(tf.constant([1.,2.,3.]).dtype)
print(tf.constant([1,2,3]).dtype)
print(torch.tensor([1.,2.,3.]).dtype)
print(torch.tensor([1,2,3]).dtype)

float64
int64
<dtype: 'float32'>
<dtype: 'int32'>
torch.float32
torch.int64


## 1-1. multi-dimensioinal array!

In [ ]:
# nested lists result in multi-dimensional arrays
a = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)
a

2
(3, 3)
8
9
int64


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
# print(tensor.itemsize)  #error. not supported
# print(tensor.size)      #error. not supported
print(tensor.dtype)
tensor

tf.Tensor(2, shape=(), dtype=int32)
2
<dtype: 'int64'>


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])>

In [ ]:
p = torch.tensor(a)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size())    # not attribute but method
print(p.dtype)
p

2
torch.Size([3, 3])
8
torch.Size([3, 3])
torch.int64


tensor([[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]])

## 1-2. tensor를 특정 값으로 초기화하기

`zeros`,`ones`, and `full` (or `fill`)

In [ ]:
a = np.zeros((3,2)) # default dtype = float64
# a = np.zeros(shape=(4,4),dtype=np.uint8)
print(a.dtype)
a

float64


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a_tf = tf.zeros(shape=(3,2)) #default dtype = float32
print(a_tf.dtype)
a_tf
# a_tf.numpy()

<dtype: 'float32'>


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a_tf.numpy() # 다시 numpy array로

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [ ]:
p = torch.zeros(size=(3,2)) # shape 대신에 size
print(p.dtype)
p

torch.float32


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a = np.ones((4,2,3))
print(a.dtype)
a

float64


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a_tf = tf.ones(shape=(4,2,3))
# a_tf = tf.ones((4,2), dtype=tf.int64)
print(a_tf.dtype)
a_tf

<dtype: 'float32'>


<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
p = torch.ones(size=(4,2,3))
print(p.dtype)
p

torch.float32


tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
a = np.full((1,3),255)
print(a.dtype)
a

int64


array([[255, 255, 255]])

In [ ]:
a_tf = tf.fill((1,3),255) # not full, but fill
print(a_tf.dtype) # default int32
a_tf

<dtype: 'int32'>


<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[255, 255, 255]], dtype=int32)>

In [ ]:
p = torch.full((1,3),255)
print(p.dtype)
p

torch.int64


tensor([[255, 255, 255]])

## 1-3. 기존의 tensor와 같은 shape의 새로운 tensor 생성.

* 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성 (`torch`의 `tensor`도 유사.)
  * `zeros_like`, `ones_like`, and `full_like`
* `tf` 의 경우는 다음과 같음.
  * `zeors_like`, `ones_like`, and `fill`


In [ ]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape, a.dtype)

a = np.zeros_like(s)
print(a.shape, a.dtype)
a

(2, 3) int64
(2, 3) int64


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.ones_like(s)
print(a.shape, a.dtype)
a

(2, 3) int64


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.full_like(s,3.0)
print(a.dtype)
a

int64


array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
s = tf.constant([[1,2,3],[4,5,6]])
print(s.shape, s.dtype)

a = tf.zeros_like(s)
print(a.shape, a.dtype)
a

(2, 3) <dtype: 'int32'>
(2, 3) <dtype: 'int32'>


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
a = tf.ones_like(s)
print(a.shape, a.dtype)
a

(2, 3) <dtype: 'int32'>


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
a = tf.fill(s.shape,3.0) # there is not fill_like
print(a.dtype)
a

<dtype: 'float32'>


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [ ]:
s = torch.tensor([[1,2,3],[4,5,6]])
print(s.shape, s.dtype)

a = torch.zeros_like(s)
print(a.shape, a.dtype)
a

torch.Size([2, 3]) torch.int64
torch.Size([2, 3]) torch.int64


tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
a = torch.ones_like(s)
print(a.shape, a.dtype)
a

torch.Size([2, 3]) torch.int64


tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
a = torch.full_like(s,3.0)
print(a.dtype)
a

torch.int64


tensor([[3, 3, 3],
        [3, 3, 3]])

## 1-4. 기타 다른 tensor 생성 방법들.

In [41]:
print(range(0,10,1)) # only integer
print(np.arange(0,1,0.1))

range(0, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [32]:
a = np.arange(0,24,2).reshape(3,4)
print(a.dtype)
a

int64


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [39]:
a_tf = tf.constant(tf.range(0,6,0.5),shape=(3,4)) # float도 가능.
print(a_tf.dtype)
a_tf

<dtype: 'float32'>


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]], dtype=float32)>

In [34]:
a_torch = torch.arange(0,24,2).reshape(3,4)
print(a_torch.dtype)
a_torch

torch.int64


tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])

In [37]:
a = torch.arange(0.,1.,0.1)
print(a.dtype)
a

torch.float32


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])

In [27]:
a = np.linspace(1,5,6)
print(a.dtype)
print(a)
a_tf = tf.linspace(1,5,6) # float32 가 아닌 float64 인 점 주의.
print(a_tf.dtype)
b_tf = tf.dtypes.cast(a_tf,tf.float32)
print(b_tf.dtype)
print(b_tf)
a_torch = torch.linspace(1,5,6)
print(a_torch.dtype)
print(a_torch)

float64
[1.  1.8 2.6 3.4 4.2 5. ]
<dtype: 'float64'>
<dtype: 'float32'>
tf.Tensor([1.  1.8 2.6 3.4 4.2 5. ], shape=(6,), dtype=float32)
torch.float32
tensor([1.0000, 1.8000, 2.6000, 3.4000, 4.2000, 5.0000])


In [29]:
a = np.eye(5)
print(a.dtype)
print(a)
a_tf = tf.eye(5)
print(a_tf.dtype)
print(a_tf)
a_torch = torch.eye(5)
print(a_torch.dtype)
print(a_torch)

float64
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<dtype: 'float32'>
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
torch.float32
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [31]:
a = np.empty((4,2))
print(a.dtype)
print(a)
# a_tf = tf.empty((4,2)) # not working. 초기화하지 않은 배열 생성.
# print(a_tf.dtype)
# print(a_tf)
a_torch = torch.empty((4,2))
print(a_torch.dtype)
print(a_torch)

float64
[[4.86489613e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
torch.float32
tensor([[-1.7530e-27,  3.2122e-41],
        [-1.7788e-27,  3.2122e-41],
        [ 2.3694e-38,  2.3694e-38],
        [ 1.4013e-45,  0.0000e+00]])


## 1-5. 난수로 구성된 tensor 생성.

* `numpy.random`와 `torch`
  * `rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
    * d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.
  * `randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.
* `tensorflow`
  * `random.uniform(shape, minval, maxval)`
  * `random.normal(shape, mean, stddev`

In [ ]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.55619745, 0.9362871 , 0.33799696, 0.39472012],
       [0.82031192, 0.69608604, 0.40966956, 0.06170825],
       [0.11522117, 0.70339389, 0.56129158, 0.73486521]])

In [ ]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.10395992, 0.13512301, 0.675423  , 0.73898494],
       [0.17457092, 0.12481904, 0.29854405, 0.5158491 ],
       [0.6113448 , 0.76401436, 0.9410037 , 0.9026034 ]], dtype=float32)>

In [ ]:
A_torch = torch.rand(3,4)
print(A_torch.dtype)
A_torch

torch.float32


tensor([[0.1202, 0.3394, 0.0531, 0.8130],
        [0.6775, 0.9403, 0.5948, 0.0434],
        [0.9893, 0.3047, 0.9056, 0.2802]])

In [ ]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))
A

(3, 4)
0.39099669668992715 0.6554725578252034


array([[ 1.18800173, -0.43367139,  0.24757554,  0.04129676],
       [ 1.20047533, -0.18213944, -0.54281844,  1.07107274],
       [ 0.01876162,  1.05964493, -0.10636181,  1.1301228 ]])

In [ ]:
A_tf = tf.random.normal(shape=(3,4),mean=0., stddev=1.0)
print(A_tf.shape)
print(tf.math.reduce_mean(A_tf),tf.math.reduce_std(A_tf))
A_tf

(3, 4)
tf.Tensor(-0.17028458, shape=(), dtype=float32) tf.Tensor(0.8427512, shape=(), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.54476297,  0.6720979 , -0.10333953,  1.2041633 ],
       [-1.4025258 , -0.37399337, -0.72326237, -0.1586897 ],
       [-0.94473696, -0.26886743,  0.9641891 , -1.453213  ]],
      dtype=float32)>

In [ ]:
A_torch = torch.randn(3,4)
print(A_torch.dtype)
print(torch.mean(A_torch),torch.std(A_torch))
A_torch

torch.float32
tensor(0.0983) tensor(1.2766)


tensor([[-1.3746, -0.9917,  0.5398,  1.8088],
        [ 0.7293, -0.2223,  2.2469, -1.3297],
        [ 0.9531,  0.1218,  0.4540, -1.7552]])

# 2.indexing & slicing on Tensor

tensor의 element에 접근하는 것은

* indexing을 통해 하나하나에 접근하고,
* slicing을 통해 특정 영역의 element에 접근 가능함.


> `list` 등의 python의 fundamental type들과의 차이는  
> slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing 을 통한 새 값을 설정은  
> 실제로 원본이 수정되게 됨. (주의 필요.)

### 2-1.indexing

In [42]:
A = np.arange(0,12).reshape(3,4)
print(A.dtype)
A

int64


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
# A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf = tf.Variable(np.arange(0,12).reshape(3,4), dtype=tf.int32)
print(A_tf.dtype)
A_tf

<dtype: 'int32'>


<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [44]:
A_torch = torch.tensor(torch.arange(0,12).reshape(3,4))
print(A_torch.dtype)
A_torch

torch.int64


<ipython-input-44-5e1d184cde73>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  A_torch = torch.tensor(torch.arange(0,12).reshape(3,4))


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [45]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [46]:
A[2,2]

10

In [47]:
A[2,2] = 77
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 77, 11]])

In [49]:
print(A_tf)
print(f'A_tf[0] is "{A_tf[0]}"')
print(f'A_tf[0,2] is "{A_tf[0,2]}"')
print(f'A_tf[0][2] is "{A_tf[0][2]}"')

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>
A_tf[0] is "[0 1 2 3]"
A_tf[0,2] is "2"
A_tf[0][2] is "2"


In [50]:
A_tf[0,2] # scalar 이므로 shape가 비워짐. 단, type는 여전히 tensor임.

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [54]:
A_tf[2,2] = 77 # tf에서 constant 나 Variable 모두에서 안됨.
# A_tf[2,2].assign(77) # only working for Variable
A_tf

TypeError: 'ResourceVariable' object does not support item assignment

constant를 이용한 tensor는 immutable임.
(Vairable을 이용하면 다음을 통해 변경가능하나 이는 weight등으로 더 많이 사용됨.)

element-wise변경을 다음과 같이 우회하여 수행할 수는 있으나 권장하지 않음.

In [55]:
# 변경하고 싶은 위치와 값을 정의
indices = tf.constant([[2, 2]]) # (2, 2) 위치를 변경하고자 함
updates = tf.constant([77]) # 해당 위치에 넣고 싶은 값

# 업데이트 적용
A_tf = tf.tensor_scatter_nd_update(A_tf, indices, updates)
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 77, 11]], dtype=int32)>

In [56]:
print(A_torch)
print(f'A[0] is "{A_torch[0]}"')
print(f'A[0,2] is "{A_torch[0,2]}"')
print(f'A[0][2] is "{A_torch[0][2]}"')

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
A[0] is "tensor([0, 1, 2, 3])"
A[0,2] is "2"
A[0][2] is "2"


In [57]:
A_torch[2,2] = 77
A_torch

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 77, 11]])

### 2-2.slicing

In [58]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [59]:
print(A)
A[1:3,1:3] = 3*A[1:3,1:3]
A

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]


array([[  0,   1,   2,   3],
       [  4,  15,  18,   7],
       [  8,  27, 231,  11]])

In [60]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

In [61]:
print(A_tf)
print(f'A_tf[1,2:] is "{A_tf[1,2:]}"')
print(f'A_tf[1,::2] is "{A_tf[1,::2]}"')
print(f'A_tf[1,::-2] is "{A_tf[1,::-2]}"')
print(f'A_tf[1,::-1] is "{A_tf[1,::-1]}"')
print(f'A_tf[1,3:0:-1] is "{A_tf[1,3:0:-1]}"')

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]], shape=(3, 4), dtype=int32)
A_tf[1,2:] is "[6 7]"
A_tf[1,::2] is "[4 6]"
A_tf[1,::-2] is "[7 5]"
A_tf[1,::-1] is "[7 6 5 4]"
A_tf[1,3:0:-1] is "[7 6 5]"


In [62]:
# tf.Tensor인 경우엔 동작 안함. tf.Variabel이어야만 동작.
print(A_tf)
A_tf[1:3,1:3].assign(3*A_tf[1:3,1:3])
A_tf

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]], shape=(3, 4), dtype=int32)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [63]:
print(A_torch)
print(f'A[1,2:] is "{A_torch[1,2:]}"')
print(f'A[1,::2] is "{A_torch[1,::2]}"')
# print(f'A[1,::-2] is "{A_torch[1,::-2]}"') # not working. positive step 만 지원.
# print(f'A[1,::-1] is "{A_torch[1,::-1]}"') # not working. positive step 만 지원.
# print(f'A[1,3:0:-1] is "{A_torch[1,3:0:-1]}"') # not working. positive step 만 지원.

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 77, 11]])
A[1,2:] is "tensor([6, 7])"
A[1,::2] is "tensor([4, 6])"


In [64]:
print(A_torch)
A_torch[1:3,1:3] = 3*A_torch[1:3,1:3]
A_torch

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 77, 11]])


tensor([[  0,   1,   2,   3],
        [  4,  15,  18,   7],
        [  8,  27, 231,  11]])

# 3.tensor의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [68]:
a = np.ones((3,3))
c = a.astype('float32')
print(c)

print(id(a),a.dtype)
print(id(c),c.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
139647305826448 float64
139647306287696 float32


In [69]:
a.astype(np.float128)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float128)

In [71]:
c = np.uint8(a)
print(c)

print(id(a),a.dtype)
print(id(c),c.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
139647305826448 float64
139647306291728 uint8


In [72]:
a_tf = tf.random.uniform(shape=(3,4))
print(a_tf.dtype)
c_tf = tf.dtypes.cast(a_tf,tf.float64)
print(c_tf.dtype)
c_tf

<dtype: 'float32'>
<dtype: 'float64'>


<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.75253606, 0.513201  , 0.33693147, 0.06690419],
       [0.51715696, 0.37817049, 0.14953506, 0.92860281],
       [0.55306292, 0.81725132, 0.68160355, 0.39065182]])>

In [74]:
a_torch = torch.rand(3,4)
print(a_torch.dtype, id(a_torch))
c_torch = a_torch.type(torch.float64)
print(c_torch.dtype, id(c_torch))
c_torch

torch.float32 139647306362096
torch.float64 139647306413568


tensor([[0.0010, 0.5006, 0.4913, 0.3210],
        [0.7418, 0.5926, 0.6360, 0.4853],
        [0.0424, 0.3932, 0.9794, 0.0334]], dtype=torch.float64)

# 4.tensor의 `shape`변경

`reshape(new_shape)`

In [76]:
v = np.arange(4)
print(v.dtype,v.shape)
a = v.reshape(2,2)

print(v)
a[0]=777
print(v)
print(a)

int64 (4,)
[0 1 2 3]
[777 777   2   3]
[[777 777]
 [  2   3]]


In [77]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [79]:
a = np.arange(0,10,2) # [ s:e :step_size]
b = a.reshape((1,5))
print(a.shape,id(a))
print(b.shape,id(b))
b
c = a.reshape((5,1))
print(c.shape,id(c))

(5,) 139647306109968
(1, 5) 139647306110448
(5, 1) 139647306110544


In [80]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


In [83]:
a_torch = torch.tensor(a)
print(a_torch.shape, a_torch.ndim, id(a_torch))

b_torch = torch.reshape(a_torch,(5,1))
print(b_torch.shape, b_torch.ndim, id(b_torch))

c_torch = torch.reshape(a_torch,shape=(1,5))
print(c_torch.shape, c_torch.ndim, id(c_torch))

torch.Size([5]) 1 139647305629136
torch.Size([5, 1]) 2 139647306280256
torch.Size([1, 5]) 2 139647305627776


### 4-1.tensor를 1차원으로 풀어내기

`ndarray.ravel()`

In [ ]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 132036866381392
(9,) 132036866380624


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_torch = torch.tensor(a)
b_torch = a_torch.ravel()
print(a_torch.shape, id(a_torch))

print(b_torch.shape, id(b_torch))
b_torch

torch.Size([3, 3]) 132036871807888
torch.Size([9]) 132036866971888


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_tf = tf.constant(a)
b_tf = tf.reshape(a_tf,shape=(-1))
print(a_tf.shape, id(a_tf))

print(b_tf.shape, id(b_tf))
b_tf

(3, 3) 132036874255024
(9,) 132036874181920


<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

# Test01
 * 8 by 4 로 된 matrix를 만들것.
 * 해당 matrix는 2부터 시작해서 짝수들로 64보다 작거나 같은 수로 채워짐. 행부터 채울것.
 * 해당 matrix를 출력하고 나서 vector로  만들것 (shape=(32,)인 np.array)
 * 해당 vector를 다시 출력.


# Transpose

`ndarray.T`

In [ ]:
c=a.T
print(a)
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
c_tf = tf.transpose(a_tf)
print(a_tf)
print(c_tf)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int64)


In [ ]:
c_torch = a_torch.T
print(a_torch)
print(c_torch)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나.

In [ ]:
print(a)
c = a/2
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [ ]:
print(a_tf)
c_tf = a_tf/2
print(c_tf)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]], shape=(3, 3), dtype=float64)


In [ ]:
print(a_torch)
c_torch = a_torch/2
print(c_torch)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]])


In [ ]:
a = np.ones( shape=(5,3) )
print(a.dtype)
c = a + np.array([3,4,5])
print(c.dtype)
print(c)

print(np.array([3,4,5]).shape)

float64
float64
[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
(3,)


In [ ]:
print(np.array([3,4,5]).dtype)
print(np.array([3.,4.,5.]).dtype)

int64
float64


In [ ]:
a_tf = tf.ones( shape=(5,3))
print(a_tf.dtype)
c_tf = a_tf + tf.constant([3,4,5], dtype=float) # dtype을 빼고 해볼 것. tensorflow의 불편함을 느낄 수 있음.
print(c_tf)

<dtype: 'float32'>
tf.Tensor(
[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]], shape=(5, 3), dtype=float32)


In [ ]:
print(tf.constant([3,4,5]).dtype)
print(tf.constant([3.,4.,5.]).dtype)

<dtype: 'int32'>
<dtype: 'float32'>


In [ ]:
a_torch = torch.ones( size=(5,3) )
print(a_torch.dtype)
c_torch = a_torch + torch.tensor([3,4,5])
print(c_torch)

torch.float32
tensor([[4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.]])


In [ ]:
print(torch.tensor([3,4,5]).dtype)
print(torch.tensor([3.,4.,5.]).dtype)


torch.int64
torch.float32


In [ ]:
print(a.shape)
b= np.array([3,4,5,6,7])
print(b.shape)
c = a+b
print(c)

(5, 3)
(5,)


ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [ ]:
a_tf = tf.constant(a,dtype=tf.float32)
b_tf = tf.constant([3,4,5,6,7], dtype=tf.float32)
print(b_tf.shape)
c_tf = a_tf+b_tf
print(c_tf)

(5,)


InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [5,3] vs. [5] [Op:AddV2] name: 

In [ ]:
a_torch = torch.tensor(a)
print(a_torch.shape)
b_torch = torch.tensor([3,4,5,6,7])
print(b_torch.shape)
c_torch = a_torch+b_torch
print(c_torch)

torch.Size([5, 3])
torch.Size([5])


RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1

In [ ]:
b = np.array([3,4,5,6,7])
b = b.reshape(5,1)
c = a+b
print(a.shape)
print(b.shape)
print(c)

(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [ ]:
b_tf = tf.constant([3,4,5,6,7], dtype=tf.float32)
b_tf = tf.reshape(b_tf, shape=(5,1))
print(b_tf.shape)
c_tf = a_tf+b_tf
print(c_tf)

(5, 1)
tf.Tensor(
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]], shape=(5, 3), dtype=float32)


In [ ]:
b_torch = torch.tensor([3,4,5,6,7])
b_torch = b_torch.reshape(5,1)
print(b_torch.shape)
c_torch = a_torch+b_torch
print(c_torch)

torch.Size([5, 1])
tensor([[4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.]], dtype=torch.float64)
