In [1]:
import tensorflow as tf
import numpy as np
np.__version__

'1.18.5'

In [2]:
tf.__version__

'2.3.0'

`np.array ( list [,dtype])`

* list등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `floast32` : float (32bit)

In [4]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [5]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(6,)
8
6
int64


In [6]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int64'>


<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>

# 특정 값으로 초기화한 `ndarray` 생성

`zeros`,`ones`, and `full`

In [7]:
a = np.zeros((3,2))
a = np.zeros(shape=(4,4),dtype=np.uint8)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [9]:
len(a.shape)

2

In [ ]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [11]:
a = np.ones((4,2,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [12]:
a = np.full((1,3),255)
a

array([[255, 255, 255]])

In [ ]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[7, 7, 7]])>

# 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성

`zeros_like`, `ones_like`, and `full_like` 

In [13]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

# indexing & slicing

`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능함.

* list등의 python의 fundamental type들과의 차이는 slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing으로 실제로 원본이 수정되게 됨. (주의 필요.)

In [35]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [23]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [24]:
A[2,2]

10

In [27]:
A[2,2] = 77
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 77, 11]])

In [ ]:
A_tf[0,2] # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [36]:
print(A)
A[1:3,1:3] = 3*A[1:3,1:3] 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

# 난수 생성.

`np.random.rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
* d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.

`np.random.randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.


In [39]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.03720681, 0.33980477, 0.54547408, 0.49219213],
       [0.63548077, 0.46369793, 0.34433369, 0.38718278],
       [0.85647614, 0.14464167, 0.76393154, 0.69513067]])

In [ ]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.2326045 , 0.86212325, 0.21450412, 0.63753927],
       [0.8858304 , 0.7746886 , 0.24409056, 0.12157071],
       [0.27621758, 0.5567453 , 0.86174667, 0.14161468]], dtype=float32)>

In [43]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))

(3, 4)
-0.38336479231057025 0.8497921541837837


In [ ]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
A_tf

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-1.2632887 , -0.91719854]], dtype=float32)>

# `ndarray`의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [44]:
print(a)
a.dtype

[[3 3 3]
 [3 3 3]]


dtype('int64')

In [46]:
c = a.astype('float32')
print(a.dtype)
print(c)
print(id(a))
print(id(c))

int64
[[3. 3. 3.]
 [3. 3. 3.]]
140475900243360
140475781452864


In [47]:
a.astype(np.float128)

array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float128)

In [ ]:
c_tf = tf.dtypes.cast(c,tf.float32)
c_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [48]:
c = np.uint8(a)
print(c.dtype)
c
print(id(a))
print(id(c))

uint8
140475900243360
140475781453744


In [50]:
c = np.uint64(a)
print(a.dtype)
c
print(c.dtype)
c

int64
uint64


array([[3, 3, 3],
       [3, 3, 3]], dtype=uint64)

# `shape`변경

`ndarray.reshape(new_shape)`

In [53]:
v = np.arange(4)
print(v,v.shape)
a = v.reshape(2,2)
a
a[0]=777
print(v)
print(a)

[0 1 2 3] (4,)
[777 777   2   3]
[[777 777]
 [  2   3]]


In [ ]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [55]:
a = np.arange(0,10,2) # [ s:e :step_size]
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
b
c = a.reshape((5,1))
print(c.shape)

(5,)
(1, 5)
(5, 1)


In [ ]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


# ndarray를 1차원으로 풀어내기

`ndarray.ravel()`

In [57]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 140475781453664
(9,) 140475781454064


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Test01
 * 8 by 4 로 된 matrix를 만들것.
 * 해당 matrix는 2부터 시작해서 짝수들로 64보다 작거나 같은 수로 채워짐. 행부터 채울것.
 * 해당 matrix를 출력하고 나서 vector로  만들것 (shape=(32,)인 np.array)
 * 해당 vector를 다시 출력.


# Transpose

`ndarray.T`

In [71]:
c=a.T
print(a)
print(c)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나. 

In [74]:
print(a)
c = a/2
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [78]:
a = np.ones( shape=(5,3) )
c = a + np.array([3,4,5])
print(c)

print(np.array([3,4,5]).shape)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
(3,)


In [79]:
b= np.array([3,4,5,6,7])
print(b.shape)
c = a+b
print(c)

(5,)


ValueError: ignored

In [80]:
b = np.array([3,4,5,6,7])
#b = b[:,np.newaxis]
b = b.reshape(5,1)
c = a+b
print(a.shape)
print(b.shape)
print(c)

(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [69]:
c = a+np.array([3,4,5,6,7]).reshape((5,1))
print(c)

[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]
