<a href="https://colab.research.google.com/github/dsaint31x/OpenCV_Python_Tutorial/blob/master/DIP/2021/%EA%B9%80%EA%B3%A0%EC%9D%80/img_0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import cv2
import numpy as np

In [ ]:
img = cv2.imread('/content/drive/MyDrive/Classroom/3-2/ImageProcessing/SLA_image.png')
print(img.shape) # 2,3,3 -> 틀림 -> 복습 필요
img

(720, 960, 3)


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

In [ ]:
type(img)

numpy.ndarray

np.where??

이해 안됨.

In [ ]:
# 조건, 조건true면 할당하는 값=1, 조건 false면 할당하는 값=img
# 아래 둘다 같은 결과

# one_hot = np.where(img>0, 1, 0) 
one_hot = np.where(img>0, 1, img) 

print(one_hot)

[[[0 1 0]
  [0 1 0]
  [0 1 0]
  ...
  [0 1 0]
  [0 1 0]
  [0 1 0]]

 [[0 1 0]
  [0 1 0]
  [0 1 0]
  ...
  [0 1 0]
  [0 1 0]
  [0 1 0]]

 [[0 1 0]
  [0 1 0]
  [0 1 0]
  ...
  [0 1 0]
  [0 1 0]
  [0 1 0]]

 ...

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]]


In [ ]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
b = np.array([[12, 9, 83, 40],
              [73, 59, 24, 2],
              [44, 3, 18, 65]])
b

array([[12,  9, 83, 40],
       [73, 59, 24,  2],
       [44,  3, 18, 65]])

In [ ]:
np.where(a>15) # 인덱스, 즉 위치를 반환

(array([6, 7, 8, 9]),)

In [ ]:
np.where(a==10)

(array([0]),)

In [ ]:
np.where(a > 15, True, False)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

값을 반환하고 싶으면?

In [ ]:
b[np.where(b>20)]

array([83, 40, 73, 59, 24, 44, 65])

조건에 맞는 값 찾기-np.max, np.min, np.sort

In [ ]:
# np.max(a)
max(a)
np.min(a)
min(a)
np.sort(a)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

조건에 맞는 인덱스 찾기- np.argmax, np.argmin, np.argsort

In [ ]:
np.argmax(a)
np.argmin(a)
np.argsort(a) # 값이 작은 순서대로 그 위치를 반환

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])