<a href="https://colab.research.google.com/github/dsaint31x/OpenCV_Python_Tutorial/blob/master/DIP/%EC%9D%B4%EA%B0%80%EC%98%81/DIP_Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
np.__version__

'1.18.5'

`np.array ( list [,dtype])`

* list등으로 `ndarray` 생성.
* `dtype` : data type of element.
   * `float64` : default type in the numpy.
   * `uint8` : unsigned int (8bit), the most commonly used for image processing
   * `int8` : signed int (8bit)
   * `floast32` : float (32bit)

In [ ]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [ ]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(4,)
8
4
int64


In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(4,)
<dtype: 'int64'>


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

# 특정 값으로 초기화한 `ndarray` 생성

`zeros`,`ones`, and `full`

In [ ]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [ ]:
a = np.full((1,3),7)
a

array([[7, 7, 7]])

In [ ]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[7, 7, 7]])>

# 기존의 `ndarray` 와 같은 shape를 가지는 `ndarray`생성

`zeros_like`, `ones_like`, and `full_like` 

In [ ]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

# indexing & slicing

`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능함.

* list등의 python의 fundamental type들과의 차이는 slicing의 경우에 numpy는 원본을 가리키고 있어서 slicing으로 실제로 원본이 수정되게 됨. (주의 필요.)

In [ ]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [ ]:
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [ ]:
A_tf[0,2] # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [ ]:
A[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

# 난수 생성.

`np.random.rand([d0 [,d1 [ ..., dn])` : 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
* d0 , ... , dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨.

`np.random.randn([d0 [,d1 [ ..., dn])` : $\mu=0, \sigma=1$ 인 정규 분포를 따르는 난수 반환.


In [ ]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[8.44048984e-05, 6.64821718e-01, 8.82384466e-02, 9.44139257e-01],
       [7.44913023e-01, 8.88042129e-01, 1.58718567e-01, 2.69373370e-01],
       [4.51472550e-02, 3.73525208e-01, 5.69122786e-01, 5.54361243e-01]])

In [ ]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.2326045 , 0.86212325, 0.21450412, 0.63753927],
       [0.8858304 , 0.7746886 , 0.24409056, 0.12157071],
       [0.27621758, 0.5567453 , 0.86174667, 0.14161468]], dtype=float32)>

In [ ]:
A = np.random.randn(1,2) #normal distribution of which parameters are mean and standard deviation.
A

array([[-0.71279898, -1.78033241]])

In [ ]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
A_tf

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-1.2632887 , -0.91719854]], dtype=float32)>

# `ndarray`의 `dtype` 변경

`ndarray.astype(dtype)` : method. argument로 넘겨진 `dtype`로 해당 `ndarray`의 타입 변경한 `ndarray`반환

`np.uint8(ndarray)` : argument로 넘겨진 `ndarray`를 `uint8`로 변경한 새로운 `ndarray`반환

...

In [ ]:
print(a)
a.dtype

[[3 3 3]
 [3 3 3]]


dtype('int64')

In [ ]:
c = a.astype('float32')
print(a.dtype)
c
print(id(a))
print(id(c))

int64
140610013552688
140609894849312


In [ ]:
c_tf = tf.dtypes.cast(c,tf.float32)
c_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [ ]:
c = np.uint8(a)
print(c.dtype)
c
print(id(a))
print(id(c))

uint8
140610013552688
140609894481632


In [ ]:
c = np.uint64(a)
print(a.dtype)
c
print(c.dtype)

int64
uint64


# `shape`변경

`ndarray.reshape(new_hsape)`

In [ ]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [ ]:
b= np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [ ]:
a = np.arange(0,10,2)
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
b

(5,)
(1, 5)


array([[0, 2, 4, 6, 8]])

In [ ]:
a_tf = tf.constant(a)
print(a_tf.shape, tf.rank(a_tf))

b_tf = tf.reshape(a_tf,(5,1))
print(b_tf.shape, tf.rank(b_tf))

c_tf = tf.reshape(a_tf,shape=(1,5))
print(c_tf.shape, tf.rank(c_tf))

(5,) tf.Tensor(1, shape=(), dtype=int32)
(5, 1) tf.Tensor(2, shape=(), dtype=int32)
(1, 5) tf.Tensor(2, shape=(), dtype=int32)


# ndarray를 1차원으로 풀어내기

`ndarray.ravel()`

In [ ]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 140300165615488
(9,) 140300165615088


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Transpose

`ndarray.T`

In [ ]:
c=a.T
print(id(a))
print(id(c))
c

140300165615488
140300165728576


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Broadcasting

ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가진 ndarray와 연산시키는 것처럼 자동으로 elementwise연산이 수행되는 기능.
* numpy의 가장 강력한 기능 중 하나. 

In [ ]:
print(a)
c = a+2
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
a = np.ones((5,3))
c = a+np.array([3,4,5])
print(c)

b= np.array([3,4,5,6,7])
c = a+(b[:,np.newaxis])
print(b[:,np.newaxis].shape)
print(c)

c = a+np.array([3,4,5,6,7])
print(c)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


ValueError: ignored

In [ ]:
np.concatenate((a,b),0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [ ]:
np.concatenate((a,b),1)
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,22).reshape(4,3)
print(a.shape)
print(b.shape)

(4, 3)
(4, 3)


In [ ]:
c=np.stack((a,b),0)
print(c.shape)
c

(2, 4, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]])

In [ ]:
c=np.stack((a,b),1)
print(c.shape)
c

(4, 2, 3)


array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[ 3,  4,  5],
        [13, 14, 15]],

       [[ 6,  7,  8],
        [16, 17, 18]],

       [[ 9, 10, 11],
        [19, 20, 21]]])

In [ ]:
c=np.stack((a,b),2)
print(c.shape)
c

(4, 3, 2)


array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]],

       [[ 9, 19],
        [10, 20],
        [11, 21]]])

In [ ]:
c=np.stack((a,b),-1)
print(c.shape)
c

(4, 3, 2)


array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]],

       [[ 9, 19],
        [10, 20],
        [11, 21]]])

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.hsplit(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
np.hsplit(a,[3,5])

[array([0, 1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [ ]:
b = np.arage

NameError: ignored

In [ ]:
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])


In [ ]:
import scipy.linalg as sl


In [ ]:
sl.lu(A)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]), array([[ 1. ,  0. ,  0. ],
        [ 0.5,  1. ,  0. ],
        [-0.5, -0.6,  1. ]]), array([[ 6. , -4. ,  0. ],
        [ 0. , -5. , -2. ],
        [ 0. ,  0. , -0.2]]))

In [ ]:
P, L, U = sl.lu(A)

In [ ]:
U

array([[ 6. , -4. ,  0. ],
       [ 0. , -5. , -2. ],
       [ 0. ,  0. , -0.2]])

In [ ]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [-0.5, -0.6,  1. ]])

In [ ]:
np.linalg.inv(L)

array([[ 1. ,  0. ,  0. ],
       [-0.5,  1. ,  0. ],
       [ 0.2,  0.6,  1. ]])

In [ ]:
L@U

array([[ 6., -4.,  0.],
       [ 3., -7., -2.],
       [-3.,  5.,  1.]])

In [ ]:
P@L

array([[ 0.5,  1. ,  0. ],
       [-0.5, -0.6,  1. ],
       [ 1. ,  0. ,  0. ]])