<a href="https://colab.research.google.com/github/dsaint31x/OpenCV_Python_Tutorial/blob/master/DIP/2020/%EA%B9%80%EB%AF%BC%EC%A7%80/200917_DIP_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
np.__version__

'1.18.5'

In [2]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [3]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(4,)
8
4
int64


In [4]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(4,)
<dtype: 'int64'>


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [5]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [9]:
a = np.full((1,3),7)
a

array([[7, 7, 7]])

In [10]:
a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[7, 7, 7]])>

In [11]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [19]:
# indexing & slicing
A = np.arange(0, 12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [24]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0, 2] is "{A[0, 2]}"')
print(f'A[0][2] is "{A[0][2]}"')
A[2, 2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0, 2] is "2"
A[0][2] is "2"


10

In [25]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.81888994, 0.26497422, 0.87363993, 0.95449038],
       [0.34290373, 0.46463335, 0.07747271, 0.49624222],
       [0.6552343 , 0.67815729, 0.22417296, 0.57522987]])

In [26]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.03663599, 0.43880486, 0.53427005, 0.14094448],
       [0.06976247, 0.47470832, 0.8042743 , 0.6969719 ],
       [0.06963885, 0.80293536, 0.34436405, 0.580621  ]], dtype=float32)>

In [27]:
A = np.random.randn(1,2) #normal distribution of which parameters are mean and standard deviation.
A

array([[-2.46783438,  0.42349867]])

In [28]:
A_tf = tf.random.normal(shape=(1,2),mean=0., stddev=1.0)
A_tf

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 0.08947976, -0.6451376 ]], dtype=float32)>

In [29]:
#test1

Test = np.arange(2, 65, 2).reshape((8, 4))
Test

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48],
       [50, 52, 54, 56],
       [58, 60, 62, 64]])

In [30]:
v = Test.ravel()
v

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

In [32]:
print(a)
c = a+2
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [33]:
a = np.ones((5, 3))
c = a + np.array([3, 4, 5])
print(c)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [34]:
b= np.array([3,4,5,6,7])
c = a+(b[:,np.newaxis])
print(b[:,np.newaxis].shape)
print(c)

(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [36]:
c = a+np.array([3,4,5,6,7]).reshape((5, 1))
print(c)

[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]
