In [34]:
pwd

'C:\\Users\\user'

In [1]:
import tensorflow as tf
import numpy as np
np.__version__

'1.16.5'

In [2]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [3]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(4,)
4
4
int32


In [4]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(4,)
<dtype: 'int32'>


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [5]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
# a_tf = tf.constant(a)
a_tf = tf.zeros(shape=(3,2))
a_tf
# a_tf.numpy()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
a = np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
a_tf = tf.ones((4,2), dtype=tf.int64)
a_tf

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)>

In [9]:

a = np.full((1,3),7)
a

array([[7, 7, 7]])

In [10]:

a_tf = tf.constant(a)
a_tf

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 7, 7]])>

In [11]:

s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [13]:

a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [14]:
rgb = np.zeros((256,128,3))
rgb

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [17]:
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [20]:
A[2,2]

10

In [21]:

print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [22]:

A[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [23]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

In [24]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.15104458, 0.90114232, 0.35633076, 0.24854222],
       [0.77001348, 0.77438635, 0.57485383, 0.76141099],
       [0.68609589, 0.17270172, 0.35945935, 0.15574554]])

In [25]:
m = np.arange(2,65,2)
n = m.reshape((8,4))
print(n)


[[ 2  4  6  8 10 12 14 16]
 [18 20 22 24 26 28 30 32]
 [34 36 38 40 42 44 46 48]
 [50 52 54 56 58 60 62 64]]


In [27]:
n_vector = np.ravel(n)
print(n_vector, n_vector.shape)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64] (32,)


In [30]:
print(a)
c = a+2
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [31]:

a = np.ones((5,3))
c = a+np.array([3,4,5])
print(c)


[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [33]:
a = np.ones((5,3))
c = a+np.array([3,4,5])
print(c)

# b= np.array([3,4,5,6,7])
# c = a+(b[:,np.newaxis])
# print(b[:,np.newaxis].shape)
# print(c)

# c = a+np.array([3,4,5,6,7])
# print(c)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
