In [1]:
import cv2

In [2]:
img = cv2.imread('images/lena.png')
type(img)

numpy.ndarray

- ndim : # of dimension
- shappe : tuple로 각 차원의 크기를 보여줌
- size : # of elements
- dtype : data type of element
- itemsize : byte size of element

In [3]:
img.ndim

3

In [4]:
img.shape

(512, 512, 3)

In [5]:
img.size

786432

In [6]:
s = 1
for c in img.shape:
  s *= c

print(s)

786432


In [7]:
img.dtype

dtype('uint8')

In [8]:
img.itemsize

1

In [9]:
print(f'img.itemsize:{img.itemsize}bytes')

img.itemsize:1bytes


In [10]:
import numpy as np
np.__version__

'1.21.2'

In [11]:
a = np.array([1,2,3,4])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int64')

기본적으로 `integer`를 위해선 dtype을 `int64`를 사용(버전에 따라 `int32`도 있음)

In [13]:
a = np.array([1.0,2.0,3.0,4.0])
print(type(a))
a

<class 'numpy.ndarray'>


array([1., 2., 3., 4.])

In [14]:
a.dtype

dtype('float64')

In [15]:
a = np.array([1,2,3,4], dtype=np.float16)
print(type(a))
a

<class 'numpy.ndarray'>


array([1., 2., 3., 4.], dtype=float16)

`dtype`를 지정할 때, `np.~~` 형태로 기재할 것

In [16]:
a.dtype

dtype('float16')

In [17]:
a.shape

(4,)

axis = 0 : 2개의 list  
axis = 1 : 4개의 숫자로

In [18]:
b = np.array([ [1,2,3,4],[5,6,7,8] ])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
b.shape

(2, 4)

In [20]:
b.dtype

dtype('int64')

In [21]:
c = np.array([ [1, 2, 3.85, 4],[5,6,7,8] ])
c

array([[1.  , 2.  , 3.85, 4.  ],
       [5.  , 6.  , 7.  , 8.  ]])

In [22]:
c.dtype

dtype('float64')

In [23]:
d = np.uint8(c)
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=uint8)

`3.85` 도 np.uint8로 변경시 `3`이 됨 (반올림이 아니라 버림이다)

In [24]:
d.dtype

dtype('uint8')

In [25]:
a = np.array([300,0,10])
print(a)
b = np.uint8(a)
print(b)

[300   0  10]
[44  0 10]


### 단일값으로 초기화하여 생성.
`numpy.empty(shape [,dtype])` : 초기값을 지정하지 않고 특정 크기의 ndarray 생성.  
- shape : tuple로서 생성될 ndarray의 shape를 지정.
- 각 element들이 가지는 값은 random한 garbage value 임  

`numpy.zeros(shape [,dtype])` : 0으로 초기화한 ndarray  
`numpy.ones(shape [,dtype])` : 1으로 초기화한 ndarry  
`numpy.full(shape, fill_value [,dtype])` : `fill_value`로 초기화한 ndarray

In [26]:
a = np.empty([3,4])
a

array([[6.95331892e-310, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.12465777e-312, 1.03977794e-312, 1.23075756e-312,
        1.08221785e-312],
       [1.01855798e-312, 9.76118064e-313, 1.06099790e-312,
        1.90979621e-312]])

In [27]:
a.dtype

dtype('float64')

In [28]:
a.fill(3)
a

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [29]:
a.dtype

dtype('float64')

In [30]:
b = np.zeros([3,4])
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
b.dtype

dtype('float64')

In [32]:
c = np.ones([3,4])
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
c.dtype

dtype('float64')

2by2 1로 채우고 uint8

In [34]:
a = np.ones([2,2], dtype=np.uint8)
a

array([[1, 1],
       [1, 1]], dtype=uint8)

In [35]:
a.dtype

dtype('uint8')

In [36]:
d = np.full([3,4], 8)
d

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [37]:
d.dtype

dtype('int64')

In [38]:
img.shape

(512, 512, 3)

In [39]:
a = np.ones(img.shape)
a.shape

(512, 512, 3)

### 단일값이면서 기존의 ndarray와 같은 shape의 ndarray 생성 (dtype지정해주지 않으면 기존의 array와 동일)
`empty_like(array, [dtype])`  
`ones_like(array, [dtype])`  
`zeros_like(array, [dtype])`  
`full_like(array, fill_value, [dtype])`

In [40]:
a = np.empty_like(img)
a.shape

(512, 512, 3)

In [41]:
a = np.ones_like(img)
a.shape

(512, 512, 3)

### Sequence 생성
python의 `range`와 같이 `numpy.arange`가 있음  
차이점은 반환값이 ndarray라는 점  
`numpy.arange([start=0,] stop [, step=1, dtype=float64])`

In [42]:
a = np.arange(10)
b = range(10)
print(type(a))
print(type(b)) # generator

<class 'numpy.ndarray'>
<class 'range'>


In [43]:
a = np.array(range(3,10,2))
b = np.arange(3,10,2)

print(a)
print(b)
print(type(a))
print(type(b))

[3 5 7 9]
[3 5 7 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 난수로 ndarray생성
`numpy.random.rand([d0 [,d1 [..., dn]]])`: 0~1사이의 난수를 요소값들로 가지는 배열 혹은 수 반환  
- 난수 배열의 shape의 각 크기를 인자로 넣어줌.
- 아무것도 넣어주지 않으면 수 하나 나옴  

`numpy.random.randn([d0 [,d1 [..., dn]]])`: mean=0, std=1인 normal distribution을 따르는 난수를 요소로 가지는 배열 혹은 수 반환  
- 난수 배열의 shape의 각 크기를 인자로 넣어줌.
- 아무것도 넣어주지 않으면 수 하나 나옴.

In [44]:
a = np.random.rand()
print()

-1 ~ 1 의 random 값

In [45]:
def get_rv(*d):
    return (np.random.rand(*d))*2 - 1

In [46]:
get_rv(3,4)

array([[-0.37005588, -0.22820564,  0.41189563,  0.74247295],
       [-0.00728737, -0.67526842,  0.16131512, -0.631405  ],
       [ 0.4384319 ,  0.59282924, -0.5166448 ,  0.11570992]])

In [47]:
a = np.random.randn(3000,4000)
np.mean(a)

0.00035506963084453504

In [48]:
np.std(a)

0.9999144334648689

평균이 5이고, 분산이 3인 gaussian 분포를 따르는 노이즈를 3by3

In [49]:
3*np.random.randn(3,3) + 5

array([[ 5.90782081,  7.57805546,  7.89208535],
       [ 3.95943661, 12.96258166, -2.29610957],
       [ 3.2018393 ,  2.85025134,  0.26640696]])

In [50]:
a = 3*np.random.randn(3000,3000) + 5

In [51]:
np.mean(a)

5.0002647678764705

In [52]:
np.std(a)

2.9997851251284744

### Casting (or Type Conversion)
`ndarray.astype(dtype)`  
- `dtype`으로 `ndarray`의 dtype을 변경한 새로운 ndarray 반환.  

`numpy.uintXX(array)` : unsigned int로 변경  
- `XX`는 8, 16, 32, 64  

등등..

In [53]:
a = np.arange(3,13)
print(a.shape)
print(a.dtype)
a

(10,)
int64


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
a.astype(np.uint8)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint8)

In [55]:
a.dtype

dtype('int64')

In [56]:
a = np.ones((3,4),dtype=np.uint8)
b = a.astype(np.uint16)
print(a is b)
print(a == b)

False
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [57]:
np.uint16(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint16)

In [58]:
a.dtype

dtype('uint8')

### Shape 바꾸기
`ndarray.reshape(new_shape)` : `ndarray` 값을 기준으로 shape가 `new_shape`인 ndarray 반환  

`numpy.reshape(ndarray, new_shape)` : `ndarray` 값을 기준으로 shape가 `new_shape`인 ndarray 반환  

`numpy.ravel(ndarray)` : 1차원으로 변경  

`ndarray.T` : Transpose

In [59]:
a = np.array([[1,2,3],[4,5,6]])
print(f'original:{a.shape}')
b = a.reshape((3,2))
print(f'shape of a:{a.shape}')
print(f'shape of b:{b.shape}')
b
print(id(a))
print(id(b))

original:(2, 3)
shape of a:(2, 3)
shape of b:(3, 2)
140177915363760
140177915288624


In [60]:
c = np.reshape(a, (6,1))
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [61]:
d = np.squeeze(c)
print(d.shape)
d

(6,)


array([1, 2, 3, 4, 5, 6])

In [62]:
print(a.shape)
e = np.ravel(a)
print(e.shape)
e

(2, 3)
(6,)


array([1, 2, 3, 4, 5, 6])

In [63]:
e.ndim

1

In [64]:
a.ndim

2

In [65]:
f = a.T
print(f.shape)
f

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
g = np.arange(100).reshape(2, -1, 2)
g.shape

(2, 25, 2)

In [67]:
img.shape

(512, 512, 3)

In [68]:
print(img.shape)
print(img.size)
d = np.ravel(img)
d.shape

(512, 512, 3)
786432


(786432,)

### Broad Casting
numpy를 쓰는 핵심 기능!

In [69]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
c = np.zeros_like(b.ravel())
for idx,i in enumerate(b.ravel()):
    c[idx] = i+1
c = c.reshape(b.shape)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
c = 1 + b
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
a = np.ones((2,4,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [74]:
b = np.arange(4).reshape(1,4,1)
b

array([[[0],
        [1],
        [2],
        [3]]])

In [75]:
c = a + b
c

array([[[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]],

       [[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]]])

In [76]:
a = np.ones((10, 7, 6))
#b = np.arange(2,8) # 6 마지막 axis 와 shape이 맞으면 broad casting 된다. 자동 처리
b = np.arange(10).reshape(10,1,1) # 10 나머지 axis 하려면 shape을 맞춰서 넣어줘야함
print(a.shape)
print(b.shape)
c = a + b
c 

(10, 7, 6)
(10, 1, 1)


array([[[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.,  2.]],

       [[ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.,  3.]],

       [[ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4., 

In [77]:
a = np.ones((10, 7, 6))
b = np.arange(2,8) # 6 마지막 axis 와 shape이 맞으면 broad casting 된다. 자동 처리
#b = np.arange(10).reshape(10,1,1) # 10 나머지 axis 하려면 shape을 맞춰서 넣어줘야함
print(a.shape)
print(b.shape)
c = a + b
c 

(10, 7, 6)
(6,)


array([[[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
      

3x4 (2ch) image가 있다(모든 pixel (0,0)이다). ch0 에는 +3, ch1에는 -1이 되도록 broadcast 처리를 하라.

In [78]:
a = np.zeros((3,4,2))
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [79]:
b = np.array([3, -1])

In [80]:
a + b

array([[[ 3., -1.],
        [ 3., -1.],
        [ 3., -1.],
        [ 3., -1.]],

       [[ 3., -1.],
        [ 3., -1.],
        [ 3., -1.],
        [ 3., -1.]],

       [[ 3., -1.],
        [ 3., -1.],
        [ 3., -1.],
        [ 3., -1.]]])

### indexing , slicing

In [81]:
b = np.arange(12).reshape(3,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
b[2,0]

8

In [83]:
print(b)
b[2][1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 9, 10])

In [84]:
print(b)
b[:,0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 4, 8])

indexing, slicing은 원본을 건들이기 때문에 조심해야함.

In [85]:
a = list(range(10))
b = a[3:5]
b[0] = 10
print(a)
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 4]


In [86]:
a = np.arange(10)
b = a[3:5]
b[0] = 10
print(a)
print(b)

[ 0  1  2 10  4  5  6  7  8  9]
[10  4]


In [87]:
#그래서 copy를 해줘야 원본이 바뀌지 않는다.
a = np.arange(10)
b = a[3:5].copy()
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  4]


### Fancy indexing
ndarray에 square bracket 을 통한 indexing 대신, 같은 shape의 boolean값을 가진 ndarray를 넣어주면 True인 요소들만 선택됨

In [88]:
a = np.array([
    [[0,0,255],[0,0,255],[0,0,255],[0,0,255]],
    [[0,255,0],[0,255,0],[0,255,0],[0,255,0]]
])

In [89]:
a.shape

(2, 4, 3)

In [90]:
b = (a == 255)
b

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False,  True, False],
        [False,  True, False],
        [False,  True, False],
        [False,  True, False]]])

In [91]:
d = np.zeros_like(a, dtype=np.float16)
d[b] = 1
d

array([[[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]]], dtype=float16)

In [92]:
e = np.zeros_like(a, dtype=np.float16)
e[a==255] = 1.
e

array([[[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]]], dtype=float16)

In [93]:
a[a!=255] = 128
a

array([[[128, 128, 255],
        [128, 128, 255],
        [128, 128, 255],
        [128, 128, 255]],

       [[128, 255, 128],
        [128, 255, 128],
        [128, 255, 128],
        [128, 255, 128]]])

In [94]:
a[a!=255] = 0
a

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]])

In [95]:
np.max(a - 255*d)

0.0

In [96]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [97]:
b = np.array([True, True, False])
print(b.shape)
a[b]

(3,)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [98]:
a = np.eye(3,4)
b = np.array([False, True, False])
print(b.shape)
a[b] = 100
a

(3,)


array([[  1.,   0.,   0.,   0.],
       [100., 100., 100., 100.],
       [  0.,   0.,   1.,   0.]])

In [99]:
a = np.arange(12).reshape(-1,4)
a[(a>2) & (a < 10)] = 100
a

array([[  0,   1,   2, 100],
       [100, 100, 100, 100],
       [100, 100,  10,  11]])

In [100]:
a = np.arange(12).reshape(-1,4)
a[(a<2) | (a > 10)] = 100
a

array([[100, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 100]])