In [1]:
import tensorflow as tf
import numpy as np
np.__version__

C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (

'1.17.0'

In [6]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [7]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(4,)
4
4
int32


In [8]:
a = np.zeros((3,2))
a = np.zeros(shape=(4,4),dtype=np.uint8)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [9]:
a.shape

(4, 4)

In [10]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape)

a = np.zeros_like(s)
print(a.shape)
a

(2, 3)
(2, 3)


array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
a = np.ones_like(s)
print(a.shape)
a

(2, 3)


array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
a = np.full_like(s,3.0)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [19]:
rgb = np.zeros((256,128,3))


In [33]:
A = np.arange(0,12).reshape(3,4)

print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [34]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
A[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [48]:
a = np.arange(0,10,2)
b = a.reshape((1,5))
print(a.shape)
print(b.shape)
b

(5,)
(1, 5)


array([[0, 2, 4, 6, 8]])

In [47]:
a = np.arange(1,10).reshape((3,3))
b = a.ravel()
print(a.shape, id(a))

print(b.shape, id(b))
b

(3, 3) 2147484880048
(9,) 2147484879408


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
m = np.arange(2,65,2)
n = m.reshape((8,4))
print(n)

n_vector = np.ravel(n)
print(n_vector, n_vector.shape)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64] (32,)


In [52]:

a = np.ones((5,3))
c = a+np.array([3,4,5])
print(c)

# b= np.array([3,4,5,6,7])
# c = a+(b[:,np.newaxis])
# print(b[:,np.newaxis].shape)
# print(c)

# c = a+np.array([3,4,5,6,7])
# print(c)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
