In [ ]:
!pip install numpy --upgrade

In [ ]:
import cv2

img = cv2.imread('/content/drive/MyDrive/GACHON/lena.png')
type(img)

numpy.ndarray

ndarray: n-dimensional array

gray scale(mono channel): 2차원

RGB(color space): 3차원 (x축, y축, channel)



*   ndim: # of dimentions




In [ ]:
img.ndim

3

*   shape: tuple로 각 차원의 크기를 보여줌

    (axis0, axis1, axis2.....)




In [ ]:
img.shape

(512, 512, 3)

*   size: # of elements

    786432개의 feature vector

In [ ]:
img.size

786432

*   dtype: data type of element
    
    uint8: unsinged integer 8bit (1byte)

In [ ]:
s = 1
for c in img.shape:
  s*=c

print(s)

786432


In [ ]:
img.dtype

dtype('uint8')

In [ ]:
print(f'img.itemsize : {img.itemsize}bytes') #문자열 포맷팅

img.itemsize : 1bytes


*   itemsize: byte size of element

In [ ]:
img.itemsize

1

## **Numpy array 생성하기**

초기값을 list로 가지고 있는 경우

numpy.array( list [,dtype]) : list로부터 numpy.ndarray 생성
*   list: 배열의 값을 갖고있는 list
*   dtype: data type of element
    *   int8, int16, int32  : signed integer
    *   uint8, uint16, uint32 : unsigned integer
    *   float16, float32, float64, float128 : floating point for real number
    *   complex64, complex128, complex256 : floating point for complex number
    *   bool

In [ ]:
import numpy as np #np라는 alias를 쓰는 것이 일반적이다.

a = np.array([1,2,3,4])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

python에서 모든 데이터 타입은 class임.

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array([1.,2.,3.,4.])
print(a.dtype)
a

float64


array([1., 2., 3., 4.])

위에서 보이듯이, 'numpy.array'에서 integer를 위해서는 기본적으로 numpy.

In [ ]:
import numpy as np

np.__version__

'1.21.2'

In [ ]:
a = np.array([1,2,3,4], dtype=np.float16)
print(type(a))
print(a.dtype)
a

<class 'numpy.ndarray'>
float16


array([1., 2., 3., 4.], dtype=float16)

dtype을 지정할 때, np.~~형태로 기재할 것 

In [ ]:
a.shape

(4,)

axis = 0 : 2개의 list

axis = 1 : 4개의 숫자로 구성

In [ ]:
b  = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
b.shape

(2, 4)

In [ ]:
b.dtype

dtype('int64')

In [ ]:
c = np.array([[1,2,3.94,4],[5,6,7,8]])
c

array([[1.  , 2.  , 3.94, 4.  ],
       [5.  , 6.  , 7.  , 8.  ]])

뒤에 . 이 있어서 real number

real number라서 float로 찍힘

element들 중에 1개라도 float가 있으면 float로 처리

In [ ]:
c.dtype

dtype('float64')

In [ ]:
d = np.uint8(c)
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=uint8)

In [ ]:
a = np.array([300,0,10])
print(a)
b = np.uint8(a)
print(b)

[300   0  10]
[44  0 10]


uint8은 (8bit) 0~255의 값을 나타낼 수 있기 때문에 300이 44로 표현됨

## **단일값으로 초기화하여 생성**

numpy.empty(shape [,dtype]) : 초기값을 지정하지 않고 특정 크기의 ndarray생성.
*   shape: tuple로서 생성될 ndarray의 shape을 지정
*   각 element들이 가지는 값은 random한 grabage value임

numpy.zeros(shape [,dtype]): 0으로 초기화한 ndarray

numpy.ones(shape [,dtype]) : 1로 초기화한 ndarray

numpy.full(shape fill_value [,dtype]) : fill_value로 초기화한 ndarray



In [ ]:
a = np.empty([3,4])
a

array([[4.68168830e-310, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.92966904e-033, 5.64044803e-091,
        6.40179194e+170],
       [3.61392605e+174, 1.42719369e-071, 3.99910963e+252,
        1.46030983e-319]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.fill(3)
a

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
b = np.zeros([3,4])
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c = np.ones([3,4])
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
h = np.ones([2,2],dtype = np.uint8)
h

array([[1, 1],
       [1, 1]], dtype=uint8)

In [ ]:
d = np.full([3,4],8,dtype = np.float32)
d

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]], dtype=float32)

In [ ]:
d.dtype

dtype('float32')

In [ ]:
a = np.ones(img.shape)
a.dtype

dtype('float64')

In [ ]:
a.shape

(512, 512, 3)

## 단일값이면서 기존의 ndarray와 같은 shape의 ndarray생성 (값만 바꾸어줌)

empty_like(array [,dtype])

zeros_like(array [,dtype])

ones_like(array [,dtype])

full_like(array,fill_value [,dtype])

In [ ]:
img.shape

(512, 512, 3)

In [ ]:
a = np.empty_like(img)
a.shape

(512, 512, 3)

In [ ]:
b = np.zeros_like(img)
b.shape

(512, 512, 3)

In [ ]:
c = np.ones_like(img)
c.shape

(512, 512, 3)

In [ ]:
d = np.full_like(img,8)
d.shape

(512, 512, 3)

Sequence 생성

python의 range와 같이 numpy.arange가 있음
차이점은 변환값이 ndarray라는 점임

numpy.array([start=0,] stop [, step=1, dtype=float16])

In [ ]:
a = np.arange(10)
b = range(10) # 메모리를 아끼는 면에서는 이게 편함

print(type(a))
print(type(b)) # ram에 안올림

<class 'numpy.ndarray'>
<class 'range'>


In [ ]:
a = np.array(range(3,10,2)) #둘이 같음
b = np.arange(3,10,2) # 굳이 위의 코드처럼 치지말고 한번에

print(a)
print(b)

[3 5 7 9]
[3 5 7 9]


## **난수로 ndarray생성**

numpy.random.rand([d0 [.d1 [...,dn]]]) : 0~1사이의 난수를 요소값들로 가지는 배열 혹은 수 반환.
*   난수 배열의 shape의 각 크기를 인자로 넣어줌.
*   아무것도 넣어주지 않으면 수 하나 나옴.

numpy.random.randn([d0 [.d1[...,dn]]]) : mean=0, std =1 인 normal distribution을 따르는 난수를 요소로 가지는 배열 혹은 수 반환
*    난수 배열의 shape의 각 크기를 인자로 넣어줌.
*    아무것도 넣어주지 않으면 수 하나 나옴.

In [ ]:
a = np.random.rand()
print(type(a))
a

<class 'float'>


0.08695127207714581

In [ ]:
# QUIZ
def get_rv(r,c): #r: row, c: column /// 2 by 3의 matrix 나옴
  a = np.random.rand(r,c)
  b = 2 * a - 1
  return b

get_rv(2,3)

array([[ 0.86123796, -0.61851067, -0.09864294],
       [ 0.1809227 ,  0.01341904,  0.1051054 ]])

In [ ]:
a = np.random.rand(30,40)
print(a.shape)
a

(30, 40)


array([[0.22493474, 0.99595808, 0.69753415, ..., 0.82084801, 0.83433486,
        0.50307084],
       [0.18191742, 0.94676726, 0.58214756, ..., 0.03883533, 0.26272871,
        0.15717095],
       [0.17743462, 0.06764395, 0.27610231, ..., 0.95085683, 0.08990617,
        0.49071099],
       ...,
       [0.11354695, 0.87625588, 0.63975977, ..., 0.59340215, 0.55663504,
        0.1905396 ],
       [0.20710009, 0.70776315, 0.92153052, ..., 0.19530725, 0.42054434,
        0.73606853],
       [0.79215177, 0.00883014, 0.57818788, ..., 0.14161757, 0.53771773,
        0.9839884 ]])

In [ ]:
np.mean(a) # a.mean()

0.5036585823280533

In [ ]:
np.std(a) # a.std()

0.0

In [ ]:
b = np.random.randn(30,40)
print(b.shape)
b

(30, 40)


array([[-0.80267861, -0.91785432, -2.37978155, ...,  1.80671898,
        -0.28422244, -0.0630728 ],
       [-0.59401431,  1.05255709,  0.40277724, ..., -1.40821556,
         0.75497406, -1.04631773],
       [ 0.66364448,  0.15166559,  1.56435983, ..., -1.770493  ,
         0.62930591,  0.20205202],
       ...,
       [ 1.72914602, -0.70999999, -0.95877759, ...,  1.38981415,
        -1.18866359, -2.35760755],
       [-2.35132666,  0.8615228 ,  0.86073858, ...,  0.55732625,
         0.03366137, -0.95214327],
       [-1.13092409, -1.25598376, -1.58232271, ..., -0.71070499,
         0.32102803,  0.80141848]])

In [ ]:
b.mean() # np.mean(b)

-0.016486581217633273

In [ ]:
b.std() #np.std(b)

1.01156182179778

In [ ]:
# QUIZ

def get_rv(*d):
  a = np.random.randn(*d)
  

In [ ]:
import numpy as np

a = np.random.randn(20000,2000)
a = a*3
a = a+5
print(np.mean(a))
print(np.std(a))

4.999772515926331
3.0000040187242645


## **casting**

ndarrya.astype(dtype)

numpy.unitxx(array)

numpy.intxx(array)

numpy.floatxx(array)

In [ ]:
a = np.arange(3,13)
print(a.shape)
print(a.dtype)
a

(10,)
int64


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.astype(np.uint8)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint8)

In [ ]:
a.dtype # 응,  안바뀜, 메모리 주소도 다름

dtype('int64')

In [ ]:
a = np.ones((3,4),dtype=np.uint8)
b = a.astype(np.uint16)
print(a is b)
print(a == b)

False
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## **shape 바꾸기**
ndarray.reshape(new_shape): ndarry 값을 기준으로 shape가 new_shape인 ndarray 반환

numpy.reshape(ndarray, new_shape): ndarray값을 기준으로 shape이 new_shape인 ndaray반환

numpy.ravel(ndarray): 1차원으로 변경

ndarray.T: transpose

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(f'original:{a.shape}')

b = a.reshape((2,3))
print(f'shape of a: {a.shape}')
print(f'shaep of b:{b.shape}')
b

print(id(a))
print(id(b)) #reshape해서 저장하면 다른 메모리에 저장됨

original:(2, 3)
shape of a: (2, 3)
shaep of b:(2, 3)
140576720349984
140576720410704


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c = np.reshape(a,(6,1))
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
c.ndim

2

In [ ]:
d = np.squeeze(c) #1로 되어있는 필요없는 값들은 제거해줌
d.shape

(6,)

In [ ]:
d

array([1, 2, 3, 4, 5, 6])

In [ ]:
d.ndim

1

In [ ]:
print(a.shape)
d = np.ravel(a)
print(d.shape)
d

(2, 3)
(6,)


array([1, 2, 3, 4, 5, 6])

In [ ]:
e = a.reshape((-1)) #알아서 숫자 넣으세요
e.shape

(6,)

In [ ]:
e.ndim

1

In [ ]:
e = a.T
print(e.shape)
e

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
f = np.arange(100).reshape(2,-1,2)
f.shape

(2, 25, 2)

In [ ]:
f

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59],
        [60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79],
        [80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [ ]:
f.reshape(-1) #일자로 펴줘

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
img.shape

(512, 512, 3)

In [ ]:
img

array([[[ 74, 111, 193],
        [ 79, 116, 198],
        [ 76, 113, 195],
        ...,
        [ 55,  78, 146],
        [ 55,  78, 146],
        [ 55,  78, 146]],

       [[ 77, 114, 196],
        [ 78, 115, 197],
        [ 75, 112, 194],
        ...,
        [ 57,  80, 148],
        [ 57,  80, 148],
        [ 57,  80, 148]],

       [[ 78, 115, 199],
        [ 76, 107, 192],
        [ 77, 117, 200],
        ...,
        [ 54,  80, 150],
        [ 54,  80, 147],
        [ 55,  79, 145]],

       ...,

       [[ 61,  88, 168],
        [ 63,  90, 170],
        [ 65,  95, 174],
        ...,
        [ 37,  39,  69],
        [ 36,  38,  69],
        [ 38,  40,  71]],

       [[ 61,  86, 166],
        [ 62,  89, 169],
        [ 64,  91, 171],
        ...,
        [ 36,  38,  68],
        [ 36,  38,  68],
        [ 39,  41,  71]],

       [[ 55,  81, 158],
        [ 62,  88, 165],
        [ 62,  90, 167],
        ...,
        [ 36,  39,  67],
        [ 39,  41,  71],
        [ 44,  46,  76]]

In [ ]:
print(img.size)
d = np.ravel(img) #1차원으로 변경
d.shape

786432


(786432,)

## **broad Casting**

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b = a.reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c = np.zeros_like(b.ravel())
for idx, i in enumerate(b.ravel()): #일자로 펴주고
  c[idx] = i+1 #각 item에 1을 더해주고
c = c.reshape(b.shape) # b.shape로 reshape해줌
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = 1 + b #3 by 4배열 형태인데 브로드캐스팅으로 각 item에 1을 더함
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
d = b - 2
d

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [ ]:
 e = d*2
 e

array([[-4, -2,  0,  2],
       [ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [ ]:
f = b/10
f

array([[0. , 0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6, 0.7],
       [0.8, 0.9, 1. , 1.1]])

In [ ]:
g = b**2
g

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a = np.ones((2,4,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
b = np.arange(4).reshape(1,4,1) #행과 열에 따라서 다르게 더해주고 싶다. #가운데 인덱스(4)는 맞춰준다. 1; 알아서 펴줘
b

array([[[0],
        [1],
        [2],
        [3]]])

In [ ]:
c = a + b #최소한 한 axis와 길이가 맞아야하고, 나머지는 자동을 뻥튀기
c

array([[[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]],

       [[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]]])

In [ ]:
a = np.ones((10,7,6)) 
b = np.arange(2,8) #2부터 8까지의 array가 만들어지고
# b = np.arange(10).reshape(10,1,1) # 첫번째 축에 맞출려면 이렇게
print(a.shape) 
print(b.shape)
c = a + b # 10 by 7 by 6으로 뻥튀기가되어서 브로트캐스팅이 이루어진다. 
c

(10, 7, 6)
(6,)


array([[[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.],
        [3., 4., 5., 6., 7., 8.]],

       [[3., 4., 5., 6., 7., 8.],
      

In [ ]:
#QUIZ 3x4 (2ch) image가 있다(모든 픽셀은 (0,0)이다.). ch0는 +3, ch1에는 -1

a = np.zeros((3,4,2),dtype=np.int64)
b = np.array([3,-1])
a = a + b
a

array([[[ 3, -1],
        [ 3, -1],
        [ 3, -1],
        [ 3, -1]],

       [[ 3, -1],
        [ 3, -1],
        [ 3, -1],
        [ 3, -1]],

       [[ 3, -1],
        [ 3, -1],
        [ 3, -1],
        [ 3, -1]]])

In [ ]:
a = np.arange(24).reshape(3,4,2)
a #[0,1] 채널로 묶여있고 이거 한 픽셀의 값임, 4가 너비이고, 3이 높이에 해당한다. 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

큰덩어리 3개: 3개의 행

그안에 4개의 칼럼이 있고, 2개의 채널로 이루어져있다.

In [ ]:
img.shape

(512, 512, 3)

## **indexing & slicing**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0]

0

In [ ]:
a[5]

5

In [ ]:
a[3:5]

array([3, 4])

In [ ]:
b = np.arange(12).reshape(3,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[2] #인덱스 2에 해당하는 행이 반환됨> 첫번째 엑시스의 길이

array([ 8,  9, 10, 11])

In [ ]:
b[2,0] #인덱스 2에 해당하는 행에서 첫번째 숫자 가지고와

8

In [ ]:
b[2][0] #위와 같음

8

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(b)
b[2][1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 9, 10])

In [ ]:
print(b)
b[:,0] #모든 행에서 0번째 원소만 뽑아옴

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 4, 8])

python과의 slicing차이점

In [ ]:
a = list(range(10))
b = a[3:5]
b[0] = 10
print(a) #python: 알아서 sub space에서 카피본을 만들어줌
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 4]


In [ ]:
a = np.arange(10)
b = a[3:5] #a가 바뀌는 걸 막고싶다면, b = a[3:5].copy()
b[0]=10
print(a) #카피본 안만들어줘서 a가 바뀜
print(b)

[ 0  1  2 10  4  5  6  7  8  9]
[10  4]


## **fancy indexing**
ndarray에 square brachket을 통한 indexing대신, 같은 shape의 boolean값을 가진 ndarray를 넣어주면 True인 요소들만 선택됨.

In [ ]:
a = np.array([
              [[0,0,255],[0,0,255],[0,0,255],[0,0,255]],
              [[0,255,0],[0,255,0],[0,255,0],[0,255,0]],
              #[[0,0,255],[0,0,255],[0,0,255],[0,0,255]]
              ],dtype=np.uint8)
a.shape

(2, 4, 3)

In [ ]:
c = (a==255)
print(c.dtype)
print(a.dtype)
c

bool
uint8


array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False,  True, False],
        [False,  True, False],
        [False,  True, False],
        [False,  True, False]]])

In [ ]:
d = np.zeros_like(a,dtype=np.float16)
d[c]=1 #true만 1로 싹싹 바뀜
d

array([[[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]]], dtype=float16)

In [ ]:
d = np.zeros_like(a,dtype=np.float16)
a[a==1]=255
a #255였던것이 1로 교체!

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]], dtype=uint8)

In [ ]:
d = np.zeros_like(a,dtype=np.float16)
a[a!=255] = 128
a

array([[[128, 128, 255],
        [128, 128, 255],
        [128, 128, 255],
        [128, 128, 255]],

       [[128, 255, 128],
        [128, 255, 128],
        [128, 255, 128],
        [128, 255, 128]]], dtype=uint8)

In [ ]:
np.max(a-255*d)

0.0

In [ ]:
a = np.eye(3,4) #주대각행렬을 만들어준다
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
b = np.array([True,True, False]) #첫번째 행은 참, 두번째 행은 참, 세번째 행은 0
print(b.shape)
a[b]

(3,)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
b = np.array([False, True, False]) #[]:행, [[]]:열
print(b.shape)
a[b] = [100,100,100,100] #참인 행을 100으로 채워준다.
a

(3,)


array([[  1.,   0.,   0.,   0.],
       [100., 100., 100., 100.],
       [  0.,   0.,   1.,   0.]])

In [ ]:
a[b]

array([[100., 100., 100., 100.]])

In [ ]:
a[0]

array([1., 0., 0., 0.])

In [ ]:
a = np.arange(12).reshape(-1,4) # 행이 3이라는거 -1로 자동 계산
a[(a>2) & (a<10)] = 100 # []안에있는 조건을 만족하면 싹다 100으로 바뀜
a

array([[  0,   1,   2, 100],
       [100, 100, 100, 100],
       [100, 100,  10,  11]])

In [ ]:
a = np.arange(12).reshape(-1,4)
a[(a<2) | (a>10)] = 100
a

array([[100, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 100]])