In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.4'

### `np.array(list[.dtype])`
* list 등으로 `ndarray` 생성
* `dtype`: data type of element
    * `float64`: default type in the numpy
    * `uint8`: unsigned int (8bit), the most commonly used for image processing
    * `int8`: signed int (8bit)
    * `float32`: float (32bit)
    
> 의료 영상에서는 주로 unint8 type이 압도적으로 많이 사용됨.

In [5]:

t = (1,2, 3, 4)
a = np.array(t)

print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [6]:
print(a.ndim) # number of dimensions (tensorflow에서는 rank 개념), 몇 개의 축? 
print(a.shape) # 각각의 축이 몇개의 element로 구성?, --> 한 개의 축에 4개의 element
print(a.itemsize) # bytes 
print(a.size)
print(a.dtype)

1
(4,)
4
4
int32


## 특정 값으로 초기화한 `ndarray` 생성
* `np.zeros(shape, default=float)`
* `np.ones(shape)`
* `np.full((shape), wanted value)`

In [7]:
a = np.zeros((3, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
b = np.zeros(shape=(4, 4), dtype=np.uint8)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [9]:
# n dimension
len(a.shape)

2

In [10]:
c = np.ones((4, 2, 3))
c

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
d = np.full((1, 3), 7)
d

array([[7, 7, 7]])

## 기존의 `ndarray`와 같은 shape를 가지는 `ndarray` 생성
* `zeros_like`
* `ones_like`
* `full_like`

In [16]:
test = np.zeros((256, 128, 3))
print(test.shape)

(256, 128, 3)


## indexing & slicing (오늘하는 것 중에 가장 핵심적인 개념!)
`ndarray`의 element에 접근하는 것은 indexing을 통해 하나하나에 접근하고, slicing을 통해 특정 영역의 element에 접근 가능

python에서 slicing은 새롭게 만들어짐
* list등의 python의 fundamental type과의 차이: slicing의 경우 numpy는 원본을 가리키고 있어 slicing으로 실제 원본이 수정되게 됨.  

In [18]:
A = np.arange(0, 12).reshape(3, -1) # -1: 알아서 채워줘

In [19]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
A = np.arange(0, 12).reshape(3, 4)

In [21]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
print("A[0] is {}".format(A[0]))
print("A[0, 2] is {}".format(A[0, 2]))
print("A[0][2] is {}".format(A[0][2]))

A[0] is [0 1 2 3]
A[0, 2] is 2
A[0][2] is 2


In [23]:
A[2, 2]

10

In [25]:
# index값 변경하기
A[2, 2]=77
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 77, 11]])

In [26]:
print(A)
A[1:3, ::-1] # 뒤집기

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]


array([[ 7,  6,  5,  4],
       [11, 77,  9,  8]])

In [27]:
A[1:3, 1:3] = 777 # 1, 2번째 행 1, 2번째 열
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

## 난수 생성
* `np.random.rand([d0[, d1[..., dn])`: 0~1 사이의 수들이 균일한 확률로 선택되어 반환
    * 

In [28]:
np_rand = np.random.rand(3, 4)
print(np_rand.dtype)
np_rand

float64


array([[0.04187232, 0.33091239, 0.66004542, 0.1838159 ],
       [0.77941971, 0.02818   , 0.56494638, 0.93945169],
       [0.0395924 , 0.9814188 , 0.62067712, 0.86898146]])

In [30]:
np_norm = np.random.randn(3, 4)
print(np_norm.dtype)
np_norm

float64


array([[ 0.49052112,  0.78363624,  0.70586386, -1.27839514],
       [ 0.43742672,  0.31447362,  0.74957392,  0.18857335],
       [ 0.85883576,  1.6098992 , -0.86416941, -1.5263033 ]])

In [31]:
print(np.mean(np_norm), np.std(np_norm))
# 가우시안 mean=0에 가깝게, std=1에 가깝게

0.2058279954787404 0.9024168591649977


In [32]:
a = np.full((2, 3), 3, dtype='int64')
a

array([[3, 3, 3],
       [3, 3, 3]], dtype=int64)

In [33]:
# ndarray의 dtype 변경하기

c = a.astype('float32')
print(a.dtype)
print(c)
print(id(a))
print(id(c))

int64
[[3. 3. 3.]
 [3. 3. 3.]]
2006753286064
2006759523392


In [35]:
c = np.uint8(a)
print(c)

[[3 3 3]
 [3 3 3]]


## `ndarray`를 1차원으로 풀어내기
* ### `ndarray.ravel()`

In [36]:
a = np.arange(1, 10).reshape((3, 3))
b = a.ravel()

print(a.shape, id(a))
a
print(b.shape, id(b))
b

(3, 3) 2006759524272
(9,) 2006759524352


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
import random

`np.arange(start, end+1, step)`

In [39]:
test2 = np.arange(2, 65, 2).reshape((8, 4))
test2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48],
       [50, 52, 54, 56],
       [58, 60, 62, 64]])

In [40]:
test2 = test2.ravel()
test2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

## Transpose
* ### `ndarray.T`

## Broadcasting
ndarray와 scalar와 연산시킬때, 해당 ndarray와 같은 shape이면서 해당 scalar의 값을 가ㅣㄴ ndarray와 연산시키는 것처럼 자동으로 

In [42]:
a = np.ones((5, 3))
print(a)
c = a/2
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [43]:
a = np.ones((5, 3))
c = a + np.array([3, 4, 5])
print(c)

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [44]:
# broadcast에서 주의할 점

b = np.array([3, 4, 5, 6, 7])
c = a+b
print(c)

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [45]:
b = b.reshape(5, 1)
c = a+b
print(a.shape)
print(b.shape)
print(c)

(5, 3)
(5, 1)
[[4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]
